Libaries/Tools

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
import sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix, classification_report
import optuna
from sklearn.model_selection import StratifiedKFold, cross_val_score

c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

LOAD DATASET

In [2]:
#dataset
matches = pd.read_csv('C:/Users/mikko/OneDrive/python_projektit/ML_dec_tree_football/data_csv/Matches.csv')

C:\Users\mikko\AppData\Local\Temp\ipykernel_18172\583763451.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  matches = pd.read_csv('C:/Users/mikko/OneDrive/python_projektit/ML_dec_tree_football/data_csv/Matches.csv')

DROP COLUMNS AND FILL_EMPTY

In [3]:
matches_cleaned = matches.drop(columns=['MatchTime', 'HomeFouls', 'AwayFouls',
    'HomeYellow', 'AwayYellow', 'HomeRed', 'AwayRed',
    'MaxHome', 'MaxDraw', 'MaxAway',
    'Over25', 'Under25', 'MaxOver25', 'MaxUnder25',
    'HandiSize', 'HandiHome', 'HandiAway',
    'C_LTH', 'C_LTA', 'C_VHD', 'C_VAD',
    'C_HTB', 'C_PHB'
])

matches_cleaned = matches_cleaned.dropna()

FILTER AND REPLACE VALUES

In [4]:
matches_cleaned = matches_cleaned[matches_cleaned['Division'] == 'E0']
matches_cleaned['MatchDate'] = pd.to_datetime(matches_cleaned['MatchDate'])

matches_cleaned[['HomeTeam', 'AwayTeam']] = (
    matches_cleaned[['HomeTeam', 'AwayTeam']]
        .replace({
            "Nott'm Forest": "Nottingham Forest",
            "Nottm Forest": "Nottingham Forest"
        })
)

matches_cleaned['HomePoints'] = matches_cleaned['FTResult'].map({
    'H': 3,
    'D': 1,
    'A': 0
})

matches_cleaned['AwayPoints'] = matches_cleaned['FTResult'].map({
    'H': 0,
    'D': 1,
    'A': 3
})

matches_cleaned['FTResult'] = matches_cleaned['FTResult'].map({
    'H': 0,
    'D': 1,
    'A': 2
})

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

matches_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9325 entries, 154 to 230510
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Division     9325 non-null   object
 1   MatchDate    9325 non-null   datetime64[ns]
 2   HomeTeam     9325 non-null   object
 3   AwayTeam     9325 non-null   object
 4   HomeElo      9325 non-null   float64
 5   AwayElo      9325 non-null   float64
 6   Form3Home    9325 non-null   float64
 7   Form5Home    9325 non-null   float64
 8   Form3Away    9325 non-null   float64
 9   Form5Away    9325 non-null   float64
 10  FTHome       9325 non-null   float64
 11  FTAway       9325 non-null   float64
 12  FTResult     9325 non-null   int64
 13  HTHome       9325 non-null   float64
 14  HTAway       9325 non-null   float64
 15  HTResult     9325 non-null   object
 16  HomeShots    9325 non-null   float64
 17  AwayShots    9325 non-null   float64
 18  HomeTarget   9325 non-null   float64
 19  AwayTarget   9325 non-null   float64
 20  HomeCorners  9325 non-null   float64
 21  AwayCorners  9325 non-null   float64
 22  OddHome      9325 non-null   float64
 23  OddDraw      9325 non-null   float64
 24  OddAway      9325 non-null   float64
 25  HomePoints   9325 non-null   int64
 26  AwayPoints   9325 non-null   int64
dtypes: datetime64[ns](1), float64(19), int64(3), object(4)
memory usage: 2.0+ MB

In [6]:
matches_cleaned['margin'] = 1 / matches_cleaned['OddHome'] + 1 / matches_cleaned['OddDraw'] + 1 / matches_cleaned['OddAway']
matches_cleaned['HomeOdds'] = 1 / matches_cleaned['OddHome'] / matches_cleaned['margin']
matches_cleaned['DrawOdds'] = 1 / matches_cleaned['OddDraw'] / matches_cleaned['margin']
matches_cleaned['AwayOdds'] = 1 / matches_cleaned['OddAway'] / matches_cleaned['margin']

In [7]:
matches_cleaned = matches_cleaned.drop(columns=['OddHome', 'OddDraw', 'OddAway', 'margin'])

In [8]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

matches_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9325 entries, 154 to 230510
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Division     9325 non-null   object
 1   MatchDate    9325 non-null   datetime64[ns]
 2   HomeTeam     9325 non-null   object
 3   AwayTeam     9325 non-null   object
 4   HomeElo      9325 non-null   float64
 5   AwayElo      9325 non-null   float64
 6   Form3Home    9325 non-null   float64
 7   Form5Home    9325 non-null   float64
 8   Form3Away    9325 non-null   float64
 9   Form5Away    9325 non-null   float64
 10  FTHome       9325 non-null   float64
 11  FTAway       9325 non-null   float64
 12  FTResult     9325 non-null   int64
 13  HTHome       9325 non-null   float64
 14  HTAway       9325 non-null   float64
 15  HTResult     9325 non-null   object
 16  HomeShots    9325 non-null   float64
 17  AwayShots    9325 non-null   float64
 18  HomeTarget   9325 non-null   float64
 19  AwayTarget   9325 non-null   float64
 20  HomeCorners  9325 non-null   float64
 21  AwayCorners  9325 non-null   float64
 22  HomePoints   9325 non-null   int64
 23  AwayPoints   9325 non-null   int64
 24  HomeOdds     9325 non-null   float64
 25  DrawOdds     9325 non-null   float64
 26  AwayOdds     9325 non-null   float64
dtypes: datetime64[ns](1), float64(19), int64(3), object(4)
memory usage: 2.0+ MB

ROLLING AVERAGES FOR TOTAL POINTS

In [9]:
matches_cleaned['MatchDate'] = pd.to_datetime(matches_cleaned['MatchDate'])

# Sort chronologically and create stable match id
matches_cleaned = matches_cleaned.sort_values('MatchDate').reset_index(drop=True)
matches_cleaned['MatchID'] = matches_cleaned.index

# --- Long format: one row per (match, team) with points earned ---
home_long = matches_cleaned[['MatchID', 'MatchDate', 'HomeTeam', 'HomePoints']].copy()
home_long = home_long.rename(columns={'HomeTeam': 'Team', 'HomePoints': 'Points'})
home_long['Side'] = 'Home'

away_long = matches_cleaned[['MatchID', 'MatchDate', 'AwayTeam', 'AwayPoints']].copy()
away_long = away_long.rename(columns={'AwayTeam': 'Team', 'AwayPoints': 'Points'})
away_long['Side'] = 'Away'

teams_long = pd.concat([home_long, away_long], ignore_index=True)

# --- Rolling average points over last 20 games per team (BEFORE match) ---
teams_long = teams_long.sort_values(['Team', 'MatchDate', 'MatchID']).reset_index(drop=True)

g = teams_long.groupby('Team')['Points']

# rolling avg of previous 20 matches: shift to exclude current match
teams_long['RollingAvgPoints20Before'] = (
    g.apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
     .reset_index(level=0, drop=True)
)

# --- Merge back to match table as Home/Away features ---
home_feat = teams_long[teams_long['Side'] == 'Home'][['MatchID', 'RollingAvgPoints20Before']].rename(
    columns={'RollingAvgPoints20Before': 'HomeTotalPointsRoll20'}  # name kept, now rolling avg
)
away_feat = teams_long[teams_long['Side'] == 'Away'][['MatchID', 'RollingAvgPoints20Before']].rename(
    columns={'RollingAvgPoints20Before': 'AwayTotalPointsRoll20'}  # name kept, now rolling avg
)

matches_cleaned = matches_cleaned.merge(home_feat, on='MatchID', how='left')
matches_cleaned = matches_cleaned.merge(away_feat, on='MatchID', how='left')

ROLLING AVERAGES FOR HOME POINTS

In [10]:
# Ensure chronological order
matches_cleaned['MatchDate'] = pd.to_datetime(matches_cleaned['MatchDate'])
matches_cleaned = matches_cleaned.sort_values('MatchDate').reset_index(drop=True)

# --- Rolling avg of last 20 HOME matches for each team ---
matches_cleaned['HomeTeamHomePointsRolling20'] = (
    matches_cleaned
    .groupby('HomeTeam')['HomePoints']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

ROLLING AVERAGES FOR AWAY POINTS

In [11]:
matches_cleaned['AwayTeamAwayPointsRolling20'] = (
    matches_cleaned
    .groupby('AwayTeam')['AwayPoints']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

ROLLING AVERAGES FOR TOTAL SHOTS

In [12]:
# Ensure shots are numeric
matches_cleaned['HomeShots'] = pd.to_numeric(matches_cleaned['HomeShots'], errors='coerce')
matches_cleaned['AwayShots'] = pd.to_numeric(matches_cleaned['AwayShots'], errors='coerce')

# --- Long format: one row per (match, team) with shots taken in that match ---
home_long = matches_cleaned[['MatchID', 'MatchDate', 'HomeTeam', 'HomeShots']].copy()
home_long = home_long.rename(columns={'HomeTeam': 'Team', 'HomeShots': 'Shots'})
home_long['Side'] = 'Home'

away_long = matches_cleaned[['MatchID', 'MatchDate', 'AwayTeam', 'AwayShots']].copy()
away_long = away_long.rename(columns={'AwayTeam': 'Team', 'AwayShots': 'Shots'})
away_long['Side'] = 'Away'

teams_long = pd.concat([home_long, away_long], ignore_index=True)

# --- Rolling AVG shots per team over last 20 games (BEFORE match), no seasonality ---
teams_long = teams_long.sort_values(['Team', 'MatchDate', 'MatchID']).reset_index(drop=True)

g = teams_long.groupby('Team')['Shots']

teams_long['ShotsRolling20Before'] = (
    g.apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
     .reset_index(level=0, drop=True)
)

# --- Merge back to match table as Home/Away features ---
home_feat = teams_long[teams_long['Side'] == 'Home'][['MatchID', 'ShotsRolling20Before']].rename(
    columns={'ShotsRolling20Before': 'HomeTeamShotsRolling20'}
)
away_feat = teams_long[teams_long['Side'] == 'Away'][['MatchID', 'ShotsRolling20Before']].rename(
    columns={'ShotsRolling20Before': 'AwayTeamShotsRolling20'}
)

matches_cleaned = matches_cleaned.merge(home_feat, on='MatchID', how='left')
matches_cleaned = matches_cleaned.merge(away_feat, on='MatchID', how='left')
# Optional cleanup:
# matches_cleaned = matches_cleaned.drop(columns=['MatchID'])

ROLLING AVERAGE FOR HOME AND AWAY SHOTS

In [13]:
# Ensure datetime + chronological order
matches_cleaned['MatchDate'] = pd.to_datetime(matches_cleaned['MatchDate'])
matches_cleaned = matches_cleaned.sort_values('MatchDate').reset_index(drop=True)

# Shots numeric
matches_cleaned['HomeShots'] = pd.to_numeric(matches_cleaned['HomeShots'], errors='coerce')
matches_cleaned['AwayShots'] = pd.to_numeric(matches_cleaned['AwayShots'], errors='coerce')

# --- Home team: rolling avg of last 20 HOME matches (exclude current) ---
matches_cleaned['HomeTeamShotsHomeRolling20'] = (
    matches_cleaned
    .groupby('HomeTeam')['HomeShots']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

# --- Away team: rolling avg of last 20 AWAY matches (exclude current) ---
matches_cleaned['AwayTeamShotsAwayRolling20'] = (
    matches_cleaned
    .groupby('AwayTeam')['AwayShots']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

# Optional: fill early NaNs (teams with no prior home/away games)
# matches_cleaned[['HomeTeamShotsHomeRolling20', 'AwayTeamShotsAwayRolling20']] = (
#     matches_cleaned[['HomeTeamShotsHomeRolling20', 'AwayTeamShotsAwayRolling20']].fillna(0)
# )

ROLLING AVERAGE FOR SHOTS ON TARGET

In [14]:
# Ensure numeric
matches_cleaned['HomeTarget'] = pd.to_numeric(matches_cleaned['HomeTarget'], errors='coerce')
matches_cleaned['AwayTarget'] = pd.to_numeric(matches_cleaned['AwayTarget'], errors='coerce')

# Make sure sorted and MatchID exists
matches_cleaned['MatchDate'] = pd.to_datetime(matches_cleaned['MatchDate'])
matches_cleaned = matches_cleaned.sort_values('MatchDate').reset_index(drop=True)
if 'MatchID' not in matches_cleaned.columns:
    matches_cleaned['MatchID'] = matches_cleaned.index

# --- Long format ---
home_long = matches_cleaned[['MatchID','MatchDate','HomeTeam','HomeTarget']].copy()
home_long = home_long.rename(columns={'HomeTeam':'Team','HomeTarget':'TargetShots'})
home_long['Side'] = 'Home'

away_long = matches_cleaned[['MatchID','MatchDate','AwayTeam','AwayTarget']].copy()
away_long = away_long.rename(columns={'AwayTeam':'Team','AwayTarget':'TargetShots'})
away_long['Side'] = 'Away'

teams_long = pd.concat([home_long, away_long], ignore_index=True)

# --- Rolling AVG per team over last 20 matches (BEFORE match), no seasonality ---
teams_long = teams_long.sort_values(['Team','MatchDate','MatchID']).reset_index(drop=True)

g = teams_long.groupby('Team')['TargetShots']

teams_long['TargetShotsRolling20Before'] = (
    g.apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
     .reset_index(level=0, drop=True)
)

# --- Merge back ---
home_feat = teams_long[teams_long['Side']=='Home'][['MatchID','TargetShotsRolling20Before']] \
    .rename(columns={'TargetShotsRolling20Before':'HomeTeamTargetShotsRolling20'})

away_feat = teams_long[teams_long['Side']=='Away'][['MatchID','TargetShotsRolling20Before']] \
    .rename(columns={'TargetShotsRolling20Before':'AwayTeamTargetShotsRolling20'})

matches_cleaned = matches_cleaned.merge(home_feat, on='MatchID', how='left')
matches_cleaned = matches_cleaned.merge(away_feat, on='MatchID', how='left')

ROLLING AVERAGE TOTAL GOALS HOME AND AWAY TEAM

In [15]:
# Ensure numeric
matches_cleaned['FTHome'] = pd.to_numeric(matches_cleaned['FTHome'], errors='coerce')
matches_cleaned['FTAway'] = pd.to_numeric(matches_cleaned['FTAway'], errors='coerce')

# --- Long format: goals scored by each team in each match ---
home_long = matches_cleaned[['MatchID', 'MatchDate', 'HomeTeam', 'FTHome']].copy()
home_long = home_long.rename(columns={'HomeTeam': 'Team', 'FTHome': 'Goals'})
home_long['Side'] = 'Home'

away_long = matches_cleaned[['MatchID', 'MatchDate', 'AwayTeam', 'FTAway']].copy()
away_long = away_long.rename(columns={'AwayTeam': 'Team', 'FTAway': 'Goals'})
away_long['Side'] = 'Away'

teams_long = pd.concat([home_long, away_long], ignore_index=True)

# --- Rolling AVG goals per team over last 20 matches (BEFORE match), no seasonality ---
teams_long = teams_long.sort_values(['Team', 'MatchDate', 'MatchID']).reset_index(drop=True)

g = teams_long.groupby('Team')['Goals']

teams_long['GoalsRolling20Before'] = (
    g.apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
     .reset_index(level=0, drop=True)
)

# --- Merge back to match table ---
home_feat = teams_long[teams_long['Side'] == 'Home'][['MatchID', 'GoalsRolling20Before']].rename(
    columns={'GoalsRolling20Before': 'HomeTotalGoalsRolling20'}
)
away_feat = teams_long[teams_long['Side'] == 'Away'][['MatchID', 'GoalsRolling20Before']].rename(
    columns={'GoalsRolling20Before': 'AwayTotalGoalsRolling20'}
)

matches_cleaned = matches_cleaned.merge(home_feat, on='MatchID', how='left')
matches_cleaned = matches_cleaned.merge(away_feat, on='MatchID', how='left')

ROLLING AVERAGES GOALS HOME AND AWAY

In [16]:
# Ensure numeric
matches_cleaned['FTHome'] = pd.to_numeric(matches_cleaned['FTHome'], errors='coerce')
matches_cleaned['FTAway'] = pd.to_numeric(matches_cleaned['FTAway'], errors='coerce')

# --- Home team: rolling avg goals in last 20 HOME matches (exclude current) ---
matches_cleaned['HomeGoalsHomeRolling20'] = (
    matches_cleaned
    .groupby('HomeTeam')['FTHome']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

# --- Away team: rolling avg goals in last 20 AWAY matches (exclude current) ---
matches_cleaned['AwayGoalsAwayRolling20'] = (
    matches_cleaned
    .groupby('AwayTeam')['FTAway']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

# Optional: fill early NaNs
# matches_cleaned[['HomeGoalsHomeRolling20','AwayGoalsAwayRolling20']] = (
#     matches_cleaned[['HomeGoalsHomeRolling20','AwayGoalsAwayRolling20']].fillna(0)
# )

ROLLING AVERAGE GOALS CONCEDED HOME AND AWAY FOR HOME AND AWAY TEAM

In [17]:
# Ensure numeric
matches_cleaned['FTHome'] = pd.to_numeric(matches_cleaned['FTHome'], errors='coerce')
matches_cleaned['FTAway'] = pd.to_numeric(matches_cleaned['FTAway'], errors='coerce')

# --- Home team conceded at home: rolling avg conceded in last 20 HOME matches (exclude current) ---
matches_cleaned['HomeConcededHomeRolling20'] = (
    matches_cleaned
    .groupby('HomeTeam')['FTAway']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

# --- Away team conceded away: rolling avg conceded in last 20 AWAY matches (exclude current) ---
matches_cleaned['AwayConcededAwayRolling20'] = (
    matches_cleaned
    .groupby('AwayTeam')['FTHome']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

In [18]:
matches_features = matches_cleaned[['HomeElo', 'AwayElo', 
    'Form3Home', 'Form5Home', 'Form3Away', 'Form5Away', 
    'FTResult', 
    'HomeTotalPointsRoll20', 'AwayTotalPointsRoll20',
    'HomeTeamHomePointsRolling20', 'AwayTeamAwayPointsRolling20', 
    'HomeTeamShotsRolling20', 'AwayTeamShotsRolling20', 
    'HomeTeamShotsHomeRolling20', 'AwayTeamShotsAwayRolling20', 
    'HomeTeamTargetShotsRolling20', 'AwayTeamTargetShotsRolling20', 
    'HomeTotalGoalsRolling20', 'AwayTotalGoalsRolling20', 
    'HomeGoalsHomeRolling20', 'AwayGoalsAwayRolling20', 
    'HomeConcededHomeRolling20','AwayConcededAwayRolling20', 'HomeOdds', 'DrawOdds', 'AwayOdds']]

In [19]:
matches_features

,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,Form5Away,FTResult,HomeTotalPointsRoll20,AwayTotalPointsRoll20,HomeTeamHomePointsRolling20,AwayTeamAwayPointsRolling20,HomeTeamShotsRolling20,AwayTeamShotsRolling20,HomeTeamShotsHomeRolling20,AwayTeamShotsAwayRolling20,HomeTeamTargetShotsRolling20,AwayTeamTargetShotsRolling20,HomeTotalGoalsRolling20,AwayTotalGoalsRolling20,HomeGoalsHomeRolling20,AwayGoalsAwayRolling20,HomeConcededHomeRolling20,AwayConcededAwayRolling20,HomeOdds,DrawOdds,AwayOdds
0,1608.77,1579.99,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.436364,0.290909,0.272727
1,1800.17,1681.36,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.583075,0.252094,0.164831
2,1635.61,1679.18,0.0,0.0,0.0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.410959,0.294521,0.294521
3,1636.08,1630.02,0.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.440497,0.284192,0.275311
4,1782.55,1685.55,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.530864,0.265432,0.203704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9320,1799.76,1880.42,5.0,8.0,6.0,12.0,2,1.70,1.55,1.50,1.55,11.65,16.05,13.30,13.80,4.3,5.55,1.80,1.30,1.45,1.65,1.10,1.40,0.309101,0.256753,0.434146
9321,1557.66,1985.45,1.0,2.0,4.0,8.0,2,0.30,1.90,0.35,1.90,9.10,14.15,8.80,11.90,3.0,4.55,0.70,1.65,0.80,1.80,2.55,0.90,0.100538,0.162964,0.736498
9322,1882.33,1776.20,4.0,7.0,7.0,7.0,2,2.00,1.45,2.10,1.10,13.75,9.65,15.85,9.70,4.7,3.90,2.05,1.35,2.30,0.85,1.05,1.20,0.721382,0.170040,0.108578
9323,2008.67,1820.28,1.0,7.0,7.0,9.0,1,2.05,1.80,2.55,1.55,17.95,13.40,18.05,13.15,5.8,5.00,2.25,1.60,2.35,1.50,0.85,1.30,0.679776,0.168440,0.151784
9324,1739.45,1820.23,0.0,6.0,6.0,12.0,1,1.45,1.60,1.15,1.35,11.45,12.35,11.20,10.15,4.1,4.70,1.30,1.65,1.45,1.35,1.75,1.15,0.352613,0.254144,0.393243

DIFFERENCE FEATURES

In [20]:
matches_features['TotalPointsRoll20_diff'] = matches_features['AwayTotalPointsRoll20'] - matches_features['HomeTotalPointsRoll20']

matches_features['HomeAwayPointsRolling20_diff'] = matches_features['AwayTeamAwayPointsRolling20'] - matches_features['HomeTeamHomePointsRolling20']

matches_features['ShotsRolling20_diff'] = matches_features['AwayTeamShotsRolling20'] - matches_features['HomeTeamShotsRolling20']

matches_features['ShotsHomeAwayRolling20_diff'] = matches_features['AwayTeamShotsAwayRolling20'] - matches_features['HomeTeamShotsHomeRolling20']

matches_features['TargetShotsRolling20_diff'] = matches_features['AwayTeamTargetShotsRolling20'] - matches_features['HomeTeamTargetShotsRolling20']

matches_features['GoalsRolling20_diff'] = matches_features['AwayTotalGoalsRolling20'] - matches_features['HomeTotalGoalsRolling20']

matches_features['GoalsHomeAwayRolling20_diff'] = matches_features['AwayGoalsAwayRolling20'] - matches_features['HomeGoalsHomeRolling20']

matches_features['ConcededHomeAwayRolling20_diff'] = matches_features['AwayConcededAwayRolling20'] - matches_features['HomeConcededHomeRolling20']

C:\Users\mikko\AppData\Local\Temp\ipykernel_18172\991253460.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['TotalPointsRoll20_diff'] = matches_features['AwayTotalPointsRoll20'] - matches_features['HomeTotalPointsRoll20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_18172\991253460.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['HomeAwayPointsRolling20_diff'] = matches_features['AwayTeamAwayPointsRolling20'] - matches_features['HomeTeamHomePointsRolling20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_18172\991253460.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['ShotsRolling20_diff'] = matches_features['AwayTeamShotsRolling20'] - matches_features['HomeTeamShotsRolling20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_18172\991253460.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['ShotsHomeAwayRolling20_diff'] = matches_features['AwayTeamShotsAwayRolling20'] - matches_features['HomeTeamShotsHomeRolling20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_18172\991253460.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['TargetShotsRolling20_diff'] = matches_features['AwayTeamTargetShotsRolling20'] - matches_features['HomeTeamTargetShotsRolling20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_18172\991253460.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['GoalsRolling20_diff'] = matches_features['AwayTotalGoalsRolling20'] - matches_features['HomeTotalGoalsRolling20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_18172\991253460.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['GoalsHomeAwayRolling20_diff'] = matches_features['AwayGoalsAwayRolling20'] - matches_features['HomeGoalsHomeRolling20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_18172\991253460.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['ConcededHomeAwayRolling20_diff'] = matches_features['AwayConcededAwayRolling20'] - matches_features['HomeConcededHomeRolling20']

INTEGERS

In [21]:
int_cols = ['Form3Home', 'Form5Home', 'Form3Away', 'Form5Away', 'FTResult']

# convert specific columns to int
matches_features[int_cols] = matches_features[int_cols].astype('int64')

# convert the rest to float
matches_features.loc[:, ~matches_features.columns.isin(int_cols)] = matches_features.loc[:, ~matches_features.columns.isin(int_cols)].astype('float64')

C:\Users\mikko\AppData\Local\Temp\ipykernel_18172\442490929.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features[int_cols] = matches_features[int_cols].astype('int64')

FEATURES AND TARGET (X, y)

In [22]:
matches_features = matches_features.dropna()

X = matches_features.drop(['FTResult', 'HomeOdds', 'DrawOdds', 'AwayOdds'], axis=1)
y = matches_features['FTResult']

In [23]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9253 entries, 19 to 9324
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   HomeElo                         9253 non-null   float64
 1   AwayElo                         9253 non-null   float64
 2   Form3Home                       9253 non-null   int64
 3   Form5Home                       9253 non-null   int64
 4   Form3Away                       9253 non-null   int64
 5   Form5Away                       9253 non-null   int64
 6   HomeTotalPointsRoll20           9253 non-null   float64
 7   AwayTotalPointsRoll20           9253 non-null   float64
 8   HomeTeamHomePointsRolling20     9253 non-null   float64
 9   AwayTeamAwayPointsRolling20     9253 non-null   float64
 10  HomeTeamShotsRolling20          9253 non-null   float64
 11  AwayTeamShotsRolling20          9253 non-null   float64
 12  HomeTeamShotsHomeRolling20      9253 non-null   float64
 13  AwayTeamShotsAwayRolling20      9253 non-null   float64
 14  HomeTeamTargetShotsRolling20    9253 non-null   float64
 15  AwayTeamTargetShotsRolling20    9253 non-null   float64
 16  HomeTotalGoalsRolling20         9253 non-null   float64
 17  AwayTotalGoalsRolling20         9253 non-null   float64
 18  HomeGoalsHomeRolling20          9253 non-null   float64
 19  AwayGoalsAwayRolling20          9253 non-null   float64
 20  HomeConcededHomeRolling20       9253 non-null   float64
 21  AwayConcededAwayRolling20       9253 non-null   float64
 22  TotalPointsRoll20_diff          9253 non-null   float64
 23  HomeAwayPointsRolling20_diff    9253 non-null   float64
 24  ShotsRolling20_diff             9253 non-null   float64
 25  ShotsHomeAwayRolling20_diff     9253 non-null   float64
 26  TargetShotsRolling20_diff       9253 non-null   float64
 27  GoalsRolling20_diff             9253 non-null   float64
 28  GoalsHomeAwayRolling20_diff     9253 non-null   float64
 29  ConcededHomeAwayRolling20_diff  9253 non-null   float64
dtypes: float64(26), int64(4)
memory usage: 2.2 MB

TRAIN AND TEST DATA SPLIT

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    shuffle=False
)

RANDOM FOREST TRAIN

In [26]:
rf = RandomForestClassifier(
    n_estimators=1500,
    max_depth=None,
    min_samples_split=10,
    min_samples_leaf=5,
    max_features="sqrt",
    class_weight="balanced_subsample", 
    n_jobs=-1,
    random_state=42
)

rf.fit(X_train, y_train)

# Predict class + probabilities
pred_rf = rf.predict(X_test)
proba_rf = rf.predict_proba(X_test)

print("Accuracy:", accuracy_score(y_test, pred_rf))
print("LogLoss:", log_loss(y_test, proba_rf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_rf))
print("\nClassification Report:\n", classification_report(y_test, pred_rf, digits=3))

Accuracy: 0.5180983252296056
LogLoss: 0.9922140553144067

Confusion Matrix:
 [[534  72 193]
 [193  45 189]
 [178  67 380]]

Classification Report:
               precision    recall  f1-score   support

           0      0.590     0.668     0.627       799
           1      0.245     0.105     0.147       427
           2      0.499     0.608     0.548       625

    accuracy                          0.518      1851
   macro avg      0.444     0.461     0.441      1851
weighted avg      0.480     0.518     0.490      1851

In [27]:
imp = pd.Series(rf.feature_importances_, index=X_train.columns).sort_values(ascending=False)
print(imp.head(25))

TargetShotsRolling20_diff         0.051744
ShotsRolling20_diff               0.051386
AwayElo                           0.051300
HomeElo                           0.048247
ShotsHomeAwayRolling20_diff       0.046555
HomeAwayPointsRolling20_diff      0.044198
TotalPointsRoll20_diff            0.041264
GoalsHomeAwayRolling20_diff       0.038076
AwayTeamShotsRolling20            0.036753
GoalsRolling20_diff               0.036711
AwayTeamShotsAwayRolling20        0.036642
HomeTeamShotsHomeRolling20        0.036101
HomeTeamShotsRolling20            0.034982
ConcededHomeAwayRolling20_diff    0.034312
HomeTeamTargetShotsRolling20      0.034026
AwayTeamTargetShotsRolling20      0.032355
HomeGoalsHomeRolling20            0.029267
HomeConcededHomeRolling20         0.028351
AwayTotalPointsRoll20             0.027963
AwayTeamAwayPointsRolling20       0.027650
HomeTeamHomePointsRolling20       0.027443
AwayConcededAwayRolling20         0.027288
HomeTotalPointsRoll20             0.026820
AwayTotalGoalsRolling20           0.026456
HomeTotalGoalsRolling20           0.025889
dtype: float64

In [28]:
X_rf_last = X_test.iloc[[-1]]   # double brackets keep it 2D

pred_rf_last = rf.predict(X_rf_last)
proba_rf_last = rf.predict_proba(X_rf_last)

print("Predicted class:", pred_rf_last)
print("Probabilities:", proba_rf_last)

Predicted class: [2]
Probabilities: [[0.25341822 0.26727161 0.47931017]]

In [29]:
pred_y_rf = rf.predict(X_test)
proba_rf = rf.predict_proba(X_test)
proba_rf_df = pd.DataFrame(proba_rf, columns=['pred_rf_H', 'pred_rf_D', 'pred_rf_A'])
proba_rf_df

      pred_rf_H  pred_rf_D  pred_rf_A
0      0.167714   0.231159   0.601127
1      0.392062   0.345427   0.262512
2      0.261085   0.390630   0.348285
3      0.469652   0.308349   0.221999
4      0.476618   0.316039   0.207343
...         ...        ...        ...
1846   0.184994   0.312077   0.502929
1847   0.124843   0.147624   0.727533
1848   0.642881   0.228213   0.128906
1849   0.648316   0.202799   0.148885
1850   0.253418   0.267272   0.479310

[1851 rows x 3 columns]

In [30]:
Features_odds = matches_features.iloc[-len(proba_rf_df):][['HomeOdds','DrawOdds','AwayOdds']].reset_index(drop=True)

proba_rf_df = pd.concat([proba_rf_df.reset_index(drop=True), Features_odds], axis=1)

In [31]:
proba_rf_df['total_prob'] = proba_rf_df['HomeOdds'] + proba_rf_df['DrawOdds'] + proba_rf_df['AwayOdds']
proba_rf_df

,pred_rf_H,pred_rf_D,pred_rf_A,HomeOdds,DrawOdds,AwayOdds,total_prob
0,0.167714,0.231159,0.601127,0.200669,0.235097,0.564234,1.0
1,0.392062,0.345427,0.262512,0.454605,0.288920,0.256475,1.0
2,0.261085,0.390630,0.348285,0.357701,0.294966,0.347333,1.0
3,0.469652,0.308349,0.221999,0.591714,0.228777,0.179509,1.0
4,0.476618,0.316039,0.207343,0.507399,0.251043,0.241558,1.0
...,...,...,...,...,...,...,...
1846,0.184994,0.312077,0.502929,0.309101,0.256753,0.434146,1.0
1847,0.124843,0.147624,0.727533,0.100538,0.162964,0.736498,1.0
1848,0.642881,0.228213,0.128906,0.721382,0.170040,0.108578,1.0
1849,0.648316,0.202799,0.148885,0.679776,0.168440,0.151784,1.0
1850,0.253418,0.267272,0.479310,0.352613,0.254144,0.393243,1.0

In [32]:
proba_rf_rng = rf.predict_proba(X_test)

rng = np.random.default_rng(42)

pred_rf_rng = np.array([
    rng.choice(len(p), p=p) for p in proba_rf_rng
])

In [33]:
print("Accuracy:", accuracy_score(y_test, pred_rf_rng))
print("LogLoss:", log_loss(y_test, proba_rf_rng))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_rf_rng))
print("\nClassification Report:\n", classification_report(y_test, pred_rf_rng, digits=3))

Accuracy: 0.4100486223662885
LogLoss: 0.9922140553144065

Confusion Matrix:
 [[360 218 221]
 [156 130 141]
 [199 157 269]]

Classification Report:
               precision    recall  f1-score   support

           0      0.503     0.451     0.476       799
           1      0.257     0.304     0.279       427
           2      0.426     0.430     0.428       625

    accuracy                          0.410      1851
   macro avg      0.396     0.395     0.394      1851
weighted avg      0.421     0.410     0.414      1851

In [36]:

SEED = 42

def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 400, 2500),
        "max_depth": trial.suggest_int("max_depth", 4, 60),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 40),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 25),
        "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2", None]),
        "bootstrap": trial.suggest_categorical("bootstrap", [True, False]),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced", "balanced_subsample"]),
        "n_jobs": -1,
        "random_state": SEED,
    }

    model_rf = RandomForestClassifier(**params)

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

    # Optimize for probability quality (lower log loss is better)
    scores = cross_val_score(
        model_rf,
        X_train,
        y_train,
        cv=cv,
        scoring="neg_log_loss",
        n_jobs=-1
    )

    return float(np.mean(scores))  # maximize neg_log_loss

# Study
study = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=SEED)
)

study.optimize(objective, n_trials=60, show_progress_bar=True)

print("\nBest CV neg_log_loss:", study.best_value)
print("Best params:\n", study.best_params)

# Train final model with best params
rf_opt = RandomForestClassifier(
    **study.best_params,
    n_jobs=-1,
    random_state=SEED
)
rf_opt.fit(X_train, y_train)

[I 2026-03-10 21:21:18,764] A new study created in memory with name: no-name-c28f2949-3e84-4a95-a0e2-f1d09bf1ab17
Best trial: 0. Best value: -0.999542:   2%|▏         | 1/60 [00:09<09:19,  9.49s/it]

[I 2026-03-10 21:21:28,253] Trial 0 finished with value: -0.999542371958716 and parameters: {'n_estimators': 1186, 'max_depth': 58, 'min_samples_split': 30, 'min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': 'balanced_subsample'}. Best is trial 0 with value: -0.999542371958716.

Best trial: 1. Best value: -0.997586:   3%|▎         | 2/60 [00:28<14:49, 15.34s/it]

[I 2026-03-10 21:21:47,682] Trial 1 finished with value: -0.9975862205624599 and parameters: {'n_estimators': 2148, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': False, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: -0.9975862205624599.

Best trial: 1. Best value: -0.997586:   5%|▌         | 3/60 [01:02<22:40, 23.86s/it]

[I 2026-03-10 21:22:21,686] Trial 2 finished with value: -0.9985735008879381 and parameters: {'n_estimators': 1358, 'max_depth': 48, 'min_samples_split': 9, 'min_samples_leaf': 13, 'max_features': None, 'bootstrap': True, 'class_weight': 'balanced'}. Best is trial 1 with value: -0.9975862205624599.

Best trial: 3. Best value: -0.97549:   7%|▋         | 4/60 [01:08<15:41, 16.82s/it]

[I 2026-03-10 21:22:27,717] Trial 3 finished with value: -0.9754903372609925 and parameters: {'n_estimators': 1039, 'max_depth': 9, 'min_samples_split': 28, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 3 with value: -0.9754903372609925.

Best trial: 3. Best value: -0.97549:   8%|▊         | 5/60 [01:18<13:00, 14.18s/it]

[I 2026-03-10 21:22:37,225] Trial 4 finished with value: -1.0013098073293683 and parameters: {'n_estimators': 1548, 'max_depth': 14, 'min_samples_split': 39, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: -0.9754903372609925.

Best trial: 3. Best value: -0.97549:  10%|█         | 6/60 [01:24<10:15, 11.40s/it]

[I 2026-03-10 21:22:43,217] Trial 5 finished with value: -0.9770664438445245 and parameters: {'n_estimators': 1216, 'max_depth': 19, 'min_samples_split': 34, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 3 with value: -0.9754903372609925.

Best trial: 3. Best value: -0.97549:  12%|█▏        | 7/60 [01:27<07:38,  8.66s/it]

[I 2026-03-10 21:22:46,224] Trial 6 finished with value: -0.9783245587064033 and parameters: {'n_estimators': 411, 'max_depth': 50, 'min_samples_split': 29, 'min_samples_leaf': 19, 'max_features': 'sqrt', 'bootstrap': False, 'class_weight': None}. Best is trial 3 with value: -0.9754903372609925.

Best trial: 3. Best value: -0.97549:  13%|█▎        | 8/60 [01:35<07:22,  8.50s/it]

[I 2026-03-10 21:22:54,399] Trial 7 finished with value: -1.0033595482362583 and parameters: {'n_estimators': 1053, 'max_depth': 22, 'min_samples_split': 30, 'min_samples_leaf': 16, 'max_features': 'sqrt', 'bootstrap': False, 'class_weight': 'balanced'}. Best is trial 3 with value: -0.9754903372609925.

Best trial: 3. Best value: -0.97549:  15%|█▌        | 9/60 [01:50<08:49, 10.37s/it]

[I 2026-03-10 21:23:08,886] Trial 8 finished with value: -0.9933983290437102 and parameters: {'n_estimators': 1498, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False, 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: -0.9754903372609925.

Best trial: 3. Best value: -0.97549:  17%|█▋        | 10/60 [01:54<07:04,  8.49s/it]

[I 2026-03-10 21:23:13,158] Trial 9 finished with value: -1.0009009614074753 and parameters: {'n_estimators': 880, 'max_depth': 8, 'min_samples_split': 13, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': 'balanced'}. Best is trial 3 with value: -0.9754903372609925.

Best trial: 10. Best value: -0.974564:  18%|█▊        | 11/60 [02:15<10:05, 12.36s/it]

[I 2026-03-10 21:23:34,302] Trial 10 finished with value: -0.9745640610407668 and parameters: {'n_estimators': 2032, 'max_depth': 4, 'min_samples_split': 21, 'min_samples_leaf': 24, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  20%|██        | 12/60 [02:46<14:24, 18.01s/it]

[I 2026-03-10 21:24:05,227] Trial 11 finished with value: -0.9746348902197532 and parameters: {'n_estimators': 2413, 'max_depth': 5, 'min_samples_split': 22, 'min_samples_leaf': 25, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  22%|██▏       | 13/60 [03:17<17:16, 22.06s/it]

[I 2026-03-10 21:24:36,610] Trial 12 finished with value: -0.9746292462977122 and parameters: {'n_estimators': 2485, 'max_depth': 5, 'min_samples_split': 20, 'min_samples_leaf': 25, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  23%|██▎       | 14/60 [03:57<20:58, 27.36s/it]

[I 2026-03-10 21:25:16,199] Trial 13 finished with value: -0.9777827697668432 and parameters: {'n_estimators': 1925, 'max_depth': 38, 'min_samples_split': 20, 'min_samples_leaf': 25, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  25%|██▌       | 15/60 [04:23<20:16, 27.04s/it]

[I 2026-03-10 21:25:42,499] Trial 14 finished with value: -0.9745682354901326 and parameters: {'n_estimators': 2481, 'max_depth': 4, 'min_samples_split': 19, 'min_samples_leaf': 21, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  27%|██▋       | 16/60 [05:05<23:00, 31.36s/it]

[I 2026-03-10 21:26:23,915] Trial 15 finished with value: -0.978267229665682 and parameters: {'n_estimators': 1890, 'max_depth': 32, 'min_samples_split': 15, 'min_samples_leaf': 21, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  28%|██▊       | 17/60 [05:51<25:48, 36.01s/it]

[I 2026-03-10 21:27:10,714] Trial 16 finished with value: -0.9781252321978243 and parameters: {'n_estimators': 2175, 'max_depth': 25, 'min_samples_split': 16, 'min_samples_leaf': 22, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  30%|███       | 18/60 [06:32<26:14, 37.49s/it]

[I 2026-03-10 21:27:51,644] Trial 17 finished with value: -0.9785951780786517 and parameters: {'n_estimators': 1795, 'max_depth': 13, 'min_samples_split': 25, 'min_samples_leaf': 17, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  32%|███▏      | 19/60 [07:51<34:03, 49.83s/it]

[I 2026-03-10 21:29:10,237] Trial 18 finished with value: -1.8866263873108466 and parameters: {'n_estimators': 2208, 'max_depth': 39, 'min_samples_split': 24, 'min_samples_leaf': 22, 'max_features': None, 'bootstrap': False, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  33%|███▎      | 20/60 [08:11<27:16, 40.92s/it]

[I 2026-03-10 21:29:30,389] Trial 19 finished with value: -1.0073596781615826 and parameters: {'n_estimators': 1752, 'max_depth': 4, 'min_samples_split': 18, 'min_samples_leaf': 18, 'max_features': None, 'bootstrap': True, 'class_weight': 'balanced'}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  35%|███▌      | 21/60 [09:13<30:46, 47.35s/it]

[I 2026-03-10 21:30:32,726] Trial 20 finished with value: -0.9799189381569506 and parameters: {'n_estimators': 2301, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  37%|███▋      | 22/60 [09:42<26:27, 41.77s/it]

[I 2026-03-10 21:31:01,495] Trial 21 finished with value: -0.9745659622363103 and parameters: {'n_estimators': 2483, 'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 24, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  38%|███▊      | 23/60 [10:25<25:53, 41.98s/it]

[I 2026-03-10 21:31:43,966] Trial 22 finished with value: -0.9769827677375179 and parameters: {'n_estimators': 2034, 'max_depth': 9, 'min_samples_split': 23, 'min_samples_leaf': 23, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  40%|████      | 24/60 [11:22<27:58, 46.62s/it]

[I 2026-03-10 21:32:41,411] Trial 23 finished with value: -0.9780673655790132 and parameters: {'n_estimators': 2484, 'max_depth': 19, 'min_samples_split': 18, 'min_samples_leaf': 23, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  42%|████▏     | 25/60 [11:49<23:46, 40.77s/it]

[I 2026-03-10 21:33:08,528] Trial 24 finished with value: -0.9745924104319265 and parameters: {'n_estimators': 2345, 'max_depth': 4, 'min_samples_split': 13, 'min_samples_leaf': 20, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  43%|████▎     | 26/60 [12:34<23:46, 41.96s/it]

[I 2026-03-10 21:33:53,281] Trial 25 finished with value: -0.9772324486974668 and parameters: {'n_estimators': 2088, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 25, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  45%|████▌     | 27/60 [13:37<26:32, 48.26s/it]

[I 2026-03-10 21:34:56,244] Trial 26 finished with value: -1.8676274365745242 and parameters: {'n_estimators': 1687, 'max_depth': 18, 'min_samples_split': 27, 'min_samples_leaf': 23, 'max_features': None, 'bootstrap': False, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  47%|████▋     | 28/60 [14:33<26:57, 50.54s/it]

[I 2026-03-10 21:35:52,108] Trial 27 finished with value: -0.9785457351599576 and parameters: {'n_estimators': 2293, 'max_depth': 14, 'min_samples_split': 34, 'min_samples_leaf': 19, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  48%|████▊     | 29/60 [14:41<19:33, 37.84s/it]

[I 2026-03-10 21:36:00,315] Trial 28 finished with value: -1.003441218863755 and parameters: {'n_estimators': 1967, 'max_depth': 8, 'min_samples_split': 17, 'min_samples_leaf': 23, 'max_features': 'log2', 'bootstrap': True, 'class_weight': 'balanced'}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  50%|█████     | 30/60 [15:49<23:23, 46.79s/it]

[I 2026-03-10 21:37:07,975] Trial 29 finished with value: -0.9995530782513319 and parameters: {'n_estimators': 2494, 'max_depth': 56, 'min_samples_split': 20, 'min_samples_leaf': 15, 'max_features': None, 'bootstrap': True, 'class_weight': 'balanced_subsample'}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  52%|█████▏    | 31/60 [16:04<18:05, 37.45s/it]

[I 2026-03-10 21:37:23,627] Trial 30 finished with value: -1.0015130513693073 and parameters: {'n_estimators': 2240, 'max_depth': 22, 'min_samples_split': 25, 'min_samples_leaf': 21, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': 'balanced_subsample'}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  53%|█████▎    | 32/60 [16:37<16:51, 36.11s/it]

[I 2026-03-10 21:37:56,618] Trial 31 finished with value: -0.9746043491673495 and parameters: {'n_estimators': 2342, 'max_depth': 5, 'min_samples_split': 13, 'min_samples_leaf': 19, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  55%|█████▌    | 33/60 [17:04<15:00, 33.35s/it]

[I 2026-03-10 21:38:23,514] Trial 32 finished with value: -0.9745847061150898 and parameters: {'n_estimators': 2344, 'max_depth': 4, 'min_samples_split': 12, 'min_samples_leaf': 21, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  57%|█████▋    | 34/60 [17:55<16:45, 38.67s/it]

[I 2026-03-10 21:39:14,604] Trial 33 finished with value: -0.9781664802673632 and parameters: {'n_estimators': 2122, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 17, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  58%|█████▊    | 35/60 [18:58<19:09, 45.97s/it]

[I 2026-03-10 21:40:17,625] Trial 34 finished with value: -0.9794553371617614 and parameters: {'n_estimators': 2387, 'max_depth': 16, 'min_samples_split': 11, 'min_samples_leaf': 14, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 35. Best value: -0.974291:  60%|██████    | 36/60 [19:06<13:50, 34.60s/it]

[I 2026-03-10 21:40:25,682] Trial 35 finished with value: -0.9742914989887822 and parameters: {'n_estimators': 2049, 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 24, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  62%|██████▏   | 37/60 [19:18<10:35, 27.62s/it]

[I 2026-03-10 21:40:37,010] Trial 36 finished with value: -1.0055169604059664 and parameters: {'n_estimators': 2051, 'max_depth': 8, 'min_samples_split': 16, 'min_samples_leaf': 24, 'max_features': 'log2', 'bootstrap': False, 'class_weight': 'balanced_subsample'}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  63%|██████▎   | 38/60 [19:26<08:00, 21.84s/it]

[I 2026-03-10 21:40:45,370] Trial 37 finished with value: -0.9748569009194809 and parameters: {'n_estimators': 1844, 'max_depth': 16, 'min_samples_split': 21, 'min_samples_leaf': 24, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  65%|██████▌   | 39/60 [19:33<06:04, 17.37s/it]

[I 2026-03-10 21:40:52,317] Trial 38 finished with value: -1.0026005789403327 and parameters: {'n_estimators': 1615, 'max_depth': 8, 'min_samples_split': 31, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True, 'class_weight': 'balanced'}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  67%|██████▋   | 40/60 [19:42<04:56, 14.82s/it]

[I 2026-03-10 21:41:01,178] Trial 39 finished with value: -0.976772969449472 and parameters: {'n_estimators': 1405, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 22, 'max_features': 'log2', 'bootstrap': False, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  68%|██████▊   | 41/60 [19:45<03:36, 11.37s/it]

[I 2026-03-10 21:41:04,496] Trial 40 finished with value: -1.0030907875451576 and parameters: {'n_estimators': 610, 'max_depth': 7, 'min_samples_split': 19, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True, 'class_weight': 'balanced_subsample'}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  70%|███████   | 42/60 [19:53<03:03, 10.17s/it]

[I 2026-03-10 21:41:11,871] Trial 41 finished with value: -0.9752204862705135 and parameters: {'n_estimators': 2224, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  72%|███████▏  | 43/60 [20:02<02:49,  9.95s/it]

[I 2026-03-10 21:41:21,318] Trial 42 finished with value: -0.9743215811382907 and parameters: {'n_estimators': 2406, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 21, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  73%|███████▎  | 44/60 [20:13<02:43, 10.21s/it]

[I 2026-03-10 21:41:32,141] Trial 43 finished with value: -0.9748539086651613 and parameters: {'n_estimators': 2433, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 24, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  75%|███████▌  | 45/60 [20:18<02:10,  8.73s/it]

[I 2026-03-10 21:41:37,408] Trial 44 finished with value: -0.9744613247985651 and parameters: {'n_estimators': 1296, 'max_depth': 7, 'min_samples_split': 22, 'min_samples_leaf': 21, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  77%|███████▋  | 46/60 [20:24<01:48,  7.77s/it]

[I 2026-03-10 21:41:42,930] Trial 45 finished with value: -0.9749396310045075 and parameters: {'n_estimators': 1194, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 24, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  78%|███████▊  | 47/60 [20:29<01:30,  6.99s/it]

[I 2026-03-10 21:41:48,093] Trial 46 finished with value: -0.974573394835244 and parameters: {'n_estimators': 1260, 'max_depth': 7, 'min_samples_split': 22, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  80%|████████  | 48/60 [20:36<01:24,  7.06s/it]

[I 2026-03-10 21:41:55,311] Trial 47 finished with value: -1.004405225026821 and parameters: {'n_estimators': 1021, 'max_depth': 35, 'min_samples_split': 27, 'min_samples_leaf': 22, 'max_features': 'log2', 'bootstrap': False, 'class_weight': 'balanced'}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  82%|████████▏ | 49/60 [20:43<01:17,  7.06s/it]

[I 2026-03-10 21:42:02,375] Trial 48 finished with value: -0.9749640789742454 and parameters: {'n_estimators': 1519, 'max_depth': 23, 'min_samples_split': 5, 'min_samples_leaf': 25, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  83%|████████▎ | 50/60 [20:51<01:14,  7.45s/it]

[I 2026-03-10 21:42:10,752] Trial 49 finished with value: -0.9750138929630247 and parameters: {'n_estimators': 1983, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  85%|████████▌ | 51/60 [20:58<01:04,  7.22s/it]

[I 2026-03-10 21:42:17,413] Trial 50 finished with value: -0.9758738589425974 and parameters: {'n_estimators': 1334, 'max_depth': 17, 'min_samples_split': 25, 'min_samples_leaf': 18, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 51. Best value: -0.974278:  87%|████████▋ | 52/60 [21:07<01:02,  7.79s/it]

[I 2026-03-10 21:42:26,543] Trial 51 finished with value: -0.974277886862988 and parameters: {'n_estimators': 2191, 'max_depth': 6, 'min_samples_split': 22, 'min_samples_leaf': 21, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 51 with value: -0.974277886862988.

Best trial: 51. Best value: -0.974278:  88%|████████▊ | 53/60 [21:20<01:04,  9.18s/it]

[I 2026-03-10 21:42:38,981] Trial 52 finished with value: -0.9757075906657464 and parameters: {'n_estimators': 2130, 'max_depth': 44, 'min_samples_split': 21, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 51 with value: -0.974277886862988.

Best trial: 51. Best value: -0.974278:  90%|█████████ | 54/60 [21:25<00:48,  8.14s/it]

[I 2026-03-10 21:42:44,698] Trial 53 finished with value: -0.9754906310441631 and parameters: {'n_estimators': 1093, 'max_depth': 10, 'min_samples_split': 23, 'min_samples_leaf': 22, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 51 with value: -0.974277886862988.

Best trial: 54. Best value: -0.974275:  92%|█████████▏| 55/60 [23:06<02:59, 35.88s/it]

[I 2026-03-10 21:44:25,299] Trial 54 finished with value: -0.9742748203256276 and parameters: {'n_estimators': 2277, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 21, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 54 with value: -0.9742748203256276.

Best trial: 54. Best value: -0.974275:  93%|█████████▎| 56/60 [23:14<01:50, 27.58s/it]

[I 2026-03-10 21:44:33,503] Trial 55 finished with value: -0.9743534468074759 and parameters: {'n_estimators': 2208, 'max_depth': 6, 'min_samples_split': 15, 'min_samples_leaf': 18, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 54 with value: -0.9742748203256276.

Best trial: 54. Best value: -0.974275:  95%|█████████▌| 57/60 [23:26<01:08, 22.88s/it]

[I 2026-03-10 21:44:45,436] Trial 56 finished with value: -0.976120314894328 and parameters: {'n_estimators': 2262, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 17, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 54 with value: -0.9742748203256276.

Best trial: 54. Best value: -0.974275:  97%|█████████▋| 58/60 [23:37<00:38, 19.34s/it]

[I 2026-03-10 21:44:56,502] Trial 57 finished with value: -0.9760547579654901 and parameters: {'n_estimators': 2161, 'max_depth': 28, 'min_samples_split': 17, 'min_samples_leaf': 18, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 54 with value: -0.9742748203256276.

Best trial: 54. Best value: -0.974275:  98%|█████████▊| 59/60 [23:47<00:16, 16.34s/it]

[I 2026-03-10 21:45:05,848] Trial 58 finished with value: -1.006837881185493 and parameters: {'n_estimators': 1945, 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 16, 'max_features': 'sqrt', 'bootstrap': False, 'class_weight': 'balanced'}. Best is trial 54 with value: -0.9742748203256276.

Best trial: 54. Best value: -0.974275: 100%|██████████| 60/60 [23:51<00:00, 23.86s/it]

[I 2026-03-10 21:45:10,452] Trial 59 finished with value: -0.975799214452505 and parameters: {'n_estimators': 955, 'max_depth': 10, 'min_samples_split': 18, 'min_samples_leaf': 19, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 54 with value: -0.9742748203256276.

Best CV neg_log_loss: -0.9742748203256276
Best params:
 {'n_estimators': 2277, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 21, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}

RandomForestClassifier(max_depth=6, min_samples_leaf=21, min_samples_split=17,
                       n_estimators=2277, n_jobs=-1, random_state=42)

In [ ]:
# Evaluate on test set
pred_rf_opt = rf_opt.predict(X_test)
proba_rf_opt = rf_opt.predict_proba(X_test)

proba_rf_opt_df = pd.DataFrame(proba_rf_opt, columns=['pred_rf_opt_H', 'pred_rf_opt_D', 'pred_rf_opt_A'])

In [38]:
#Features_last1851 = matches_features.iloc[-len(proba_rf_df):][['HomeOdds','DrawOdds','AwayOdds']].reset_index(drop=True)

proba_rf_opt_df = pd.concat([proba_rf_opt_df.reset_index(drop=True), Features_odds], axis=1)

In [39]:
proba_rf_opt_df

,pred_rf_opt_H,pred_rf_opt_D,pred_rf_opt_A,HomeOdds,DrawOdds,AwayOdds
0,0.232151,0.237537,0.530312,0.200669,0.235097,0.564234
1,0.477574,0.283111,0.239315,0.454605,0.288920,0.256475
2,0.378812,0.300436,0.320751,0.357701,0.294966,0.347333
3,0.534428,0.265993,0.199579,0.591714,0.228777,0.179509
4,0.569641,0.258686,0.171673,0.507399,0.251043,0.241558
...,...,...,...,...,...,...
1846,0.270574,0.270043,0.459383,0.309101,0.256753,0.434146
1847,0.143190,0.134263,0.722547,0.100538,0.162964,0.736498
1848,0.710732,0.184115,0.105153,0.721382,0.170040,0.108578
1849,0.674934,0.195237,0.129829,0.679776,0.168440,0.151784
1850,0.312698,0.270151,0.417151,0.352613,0.254144,0.393243

In [41]:
print("\nTEST Accuracy:", accuracy_score(y_test, pred_rf_opt))
print("TEST LogLoss:", log_loss(y_test, proba_rf_opt))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_rf_opt))
print("\nClassification Report:\n", classification_report(y_test, pred_rf_opt, digits=3))

TEST Accuracy: 0.5353862776877364
TEST LogLoss: 0.9783339444257058

Confusion Matrix:
 [[666   0 133]
 [279   0 148]
 [300   0 325]]

Classification Report:
               precision    recall  f1-score   support

           0      0.535     0.834     0.652       799
           1      0.000     0.000     0.000       427
           2      0.536     0.520     0.528       625

    accuracy                          0.535      1851
   macro avg      0.357     0.451     0.393      1851
weighted avg      0.412     0.535     0.460      1851

c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [42]:
proba_rf_opt_rng = rf_opt.predict_proba(X_test)

rng = np.random.default_rng(42)

pred_rf_opt_rng = np.array([
    rng.choice(len(p), p=p) for p in proba_rf_opt_rng
])

In [44]:
print("TEST Accuracy:", accuracy_score(y_test, pred_rf_opt_rng))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_rf_opt_rng))
print("\nClassification Report:\n", classification_report(y_test, pred_rf_opt_rng, digits=3))

TEST Accuracy: 0.43381955699621827

Confusion Matrix:
 [[426 177 196]
 [177 119 131]
 [227 140 258]]

Classification Report:
               precision    recall  f1-score   support

           0      0.513     0.533     0.523       799
           1      0.273     0.279     0.276       427
           2      0.441     0.413     0.426       625

    accuracy                          0.434      1851
   macro avg      0.409     0.408     0.408      1851
weighted avg      0.433     0.434     0.433      1851

In [45]:
X_rf_opt_last = X_test.iloc[[-1]]   # double brackets keep it 2D

pred_rf_opt_last = rf_opt.predict(X_rf_opt_last)
proba_rf_opt_last = rf_opt.predict_proba(X_rf_opt_last)

print("Predicted class:", pred_rf_opt_last)
print("Probabilities:", proba_rf_opt_last)

Predicted class: [2]
Probabilities: [[0.31269795 0.27015091 0.41715114]]

In [48]:
model_xgb = xgb.XGBClassifier(
    objective="multi:softprob",
    num_class=3,
    n_estimators=5000,
    learning_rate=0.1,      
    max_depth=4,            
    min_child_weight=5,
    subsample=0.9,
    colsample_bytree=0.9,
    reg_lambda=1.0,
    tree_method="hist",
    eval_metric="mlogloss",
    early_stopping_rounds=200,  
    random_state=42,
)

model_xgb.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=100)

#metrics
proba_xgb = model_xgb.predict_proba(X_test)
pred_xgb = proba_xgb.argmax(axis=1)

print("Accuracy:", accuracy_score(y_test, pred_xgb))
print("LogLoss:", log_loss(y_test, proba_xgb))

print(confusion_matrix(y_test, pred_xgb))
print(classification_report(y_test, pred_xgb, digits=3))

[0]	validation_0-mlogloss:1.05977
[100]	validation_0-mlogloss:0.99796
[200]	validation_0-mlogloss:1.01566
[228]	validation_0-mlogloss:1.02070
Accuracy: 0.5283630470016207
LogLoss: 0.9833346440710494
[[658   0 141]
 [276   0 151]
 [303   2 320]]
              precision    recall  f1-score   support

           0      0.532     0.824     0.646       799
           1      0.000     0.000     0.000       427
           2      0.523     0.512     0.517       625

    accuracy                          0.528      1851
   macro avg      0.352     0.445     0.388      1851
weighted avg      0.406     0.528     0.454      1851

In [49]:
X_xgb_last = X_test.iloc[[-1]]   # double brackets keep it 2D

pred_xgb_last = model_xgb.predict(X_xgb_last)
proba_xgb_last = model_xgb.predict_proba(X_xgb_last)

print("Predicted class:", pred_xgb_last)
print("Probabilities:", proba_xgb_last)

Predicted class: [2]
Probabilities: [[0.29503167 0.24786869 0.4570997 ]]

In [55]:
proba_xgb_df = pd.DataFrame(proba_xgb, columns=['pred_xgb_H', 'pred_xgb_D', 'pred_xgb_A'])
proba_xgb_df = pd.concat([proba_xgb_df.reset_index(drop=True), Features_odds], axis=1)
proba_xgb_df

      pred_xgb_H  pred_xgb_D  pred_xgb_A  HomeOdds  DrawOdds  AwayOdds
0       0.242941    0.227392    0.529667  0.200669  0.235097  0.564234
1       0.517471    0.238349    0.244180  0.454605  0.288920  0.256475
2       0.428607    0.267793    0.303600  0.357701  0.294966  0.347333
3       0.549904    0.272061    0.178034  0.591714  0.228777  0.179509
4       0.579400    0.244972    0.175628  0.507399  0.251043  0.241558
...          ...         ...         ...       ...       ...       ...
1846    0.284734    0.269150    0.446117  0.309101  0.256753  0.434146
1847    0.163948    0.144014    0.692038  0.100538  0.162964  0.736498
1848    0.699394    0.193683    0.106923  0.721382  0.170040  0.108578
1849    0.639101    0.190935    0.169964  0.679776  0.168440  0.151784
1850    0.295032    0.247869    0.457100  0.352613  0.254144  0.393243

[1851 rows x 6 columns]

In [50]:


SEED = 42
N_CLASSES = 3

# convert y if DataFrame with one column
if hasattr(y_train, "shape") and len(y_train.shape) == 2:
    y_train = y_train.iloc[:,0]
    y_test = y_test.iloc[:,0]

def objective(trial):

    params_xgbo = {
        "objective": "multi:softprob",
        "num_class": N_CLASSES,
        "tree_method": "hist",
        "eval_metric": "mlogloss",
        "random_state": SEED,
        "n_jobs": -1,

        # hyperparameters to tune
        "n_estimators": trial.suggest_int("n_estimators", 1000, 12000),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 2, 10),
        "min_child_weight": trial.suggest_float("min_child_weight", 1.0, 20.0),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 50.0, log=True),

        "gamma": trial.suggest_float("gamma", 0.0, 10.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 5.0, log=True),

        # early stopping goes HERE for xgboost >=3
        "early_stopping_rounds": 200,
    }

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
    losses = []

    for tr_idx, va_idx in cv.split(X_train, y_train):

        X_tr = X_train.iloc[tr_idx]
        X_va = X_train.iloc[va_idx]
        y_tr = y_train.iloc[tr_idx]
        y_va = y_train.iloc[va_idx]

        model_xgb_o = xgb.XGBClassifier(**params_xgbo)

        model_xgb_o.fit(
            X_tr,
            y_tr,
            eval_set=[(X_va, y_va)],
            verbose=False
        )

        proba_xgbo = model_xgb_o.predict_proba(X_va)
        losses.append(log_loss(y_va, proba_xgbo, labels=np.arange(N_CLASSES)))

    return -np.mean(losses)


study_xgb = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=SEED)
)

study_xgb.optimize(objective, n_trials=60, show_progress_bar=True)

print("\nBest CV neg_log_loss:", study_xgb.best_value)
print("Best params:\n", study_xgb.best_params)


# ---- train final optimized model ----

best_params_xgb = {
    **study_xgb.best_params,
    "objective": "multi:softprob",
    "num_class": N_CLASSES,
    "tree_method": "hist",
    "eval_metric": "mlogloss",
    "random_state": SEED,
    "n_jobs": -1,
    "early_stopping_rounds": 200,
}

model_xgb_opt = xgb.XGBClassifier(**best_params_xgb)

model_xgb_opt.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=100
)

[I 2026-03-10 22:02:16,407] A new study created in memory with name: no-name-dc0b968a-f62d-47cc-af01-c7469a575047
Best trial: 0. Best value: -0.975016:   2%|▏         | 1/60 [00:03<03:16,  3.33s/it]

[I 2026-03-10 22:02:19,740] Trial 0 finished with value: -0.9750160324714606 and parameters: {'n_estimators': 5120, 'learning_rate': 0.2536999076681772, 'max_depth': 8, 'min_child_weight': 12.374511199743695, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.5779972601681014, 'reg_lambda': 0.0018747059221802516, 'gamma': 8.661761457749352, 'reg_alpha': 0.0016946556203947059}. Best is trial 0 with value: -0.9750160324714606.

Best trial: 1. Best value: -0.974022:   3%|▎         | 2/60 [00:11<05:41,  5.89s/it]

[I 2026-03-10 22:02:27,425] Trial 1 finished with value: -0.9740224899847473 and parameters: {'n_estimators': 8789, 'learning_rate': 0.010725209743171996, 'max_depth': 10, 'min_child_weight': 16.816410175208013, 'subsample': 0.6061695553391381, 'colsample_bytree': 0.5909124836035503, 'reg_lambda': 0.0072746531356694235, 'gamma': 3.0424224295953772, 'reg_alpha': 0.0003671474011048667}. Best is trial 1 with value: -0.9740224899847473.

Best trial: 1. Best value: -0.974022:   5%|▌         | 3/60 [00:21<07:46,  8.18s/it]

[I 2026-03-10 22:02:38,334] Trial 2 finished with value: -0.9747380761264385 and parameters: {'n_estimators': 5751, 'learning_rate': 0.02692655251486473, 'max_depth': 7, 'min_child_weight': 3.6503833523887947, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.6831809216468459, 'reg_lambda': 0.1390142035054592, 'gamma': 7.851759613930136, 'reg_alpha': 5.457028747569545e-07}. Best is trial 1 with value: -0.9740224899847473.

Best trial: 1. Best value: -0.974022:   7%|▋         | 4/60 [00:27<06:34,  7.05s/it]

[I 2026-03-10 22:02:43,651] Trial 3 finished with value: -0.9763117958733233 and parameters: {'n_estimators': 6657, 'learning_rate': 0.07500118950416987, 'max_depth': 2, 'min_child_weight': 12.54335218612733, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_lambda': 28.759721562259614, 'gamma': 9.656320330745594, 'reg_alpha': 0.10770212765048791}. Best is trial 1 with value: -0.9740224899847473.

Best trial: 1. Best value: -0.974022:   8%|▊         | 5/60 [00:50<11:56, 13.03s/it]

[I 2026-03-10 22:03:07,278] Trial 4 finished with value: -0.9747524007347831 and parameters: {'n_estimators': 4351, 'learning_rate': 0.013940346079873234, 'max_depth': 8, 'min_child_weight': 9.362897381052425, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351, 'reg_lambda': 0.0014507434860119778, 'gamma': 9.093204020787821, 'reg_alpha': 1.7828684416997836e-06}. Best is trial 1 with value: -0.9740224899847473.

Best trial: 1. Best value: -0.974022:  10%|█         | 6/60 [01:00<10:44, 11.94s/it]

[I 2026-03-10 22:03:17,109] Trial 5 finished with value: -0.9759250743728567 and parameters: {'n_estimators': 8288, 'learning_rate': 0.028869220380495747, 'max_depth': 6, 'min_child_weight': 11.387495307522313, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'reg_lambda': 4.388598863942796, 'gamma': 9.394989415641891, 'reg_alpha': 0.6082418248172017}. Best is trial 1 with value: -0.9740224899847473.

Best trial: 6. Best value: -0.973645:  12%|█▏        | 7/60 [01:02<07:41,  8.71s/it]

[I 2026-03-10 22:03:19,161] Trial 6 finished with value: -0.9736448725391161 and parameters: {'n_estimators': 7577, 'learning_rate': 0.22999586428143728, 'max_depth': 2, 'min_child_weight': 4.723674385963759, 'subsample': 0.522613644455269, 'colsample_bytree': 0.6626651653816322, 'reg_lambda': 0.06704755197530224, 'gamma': 2.713490317738959, 'reg_alpha': 0.16186864586521713}. Best is trial 6 with value: -0.9736448725391161.

Best trial: 6. Best value: -0.973645:  13%|█▎        | 8/60 [01:12<07:49,  9.02s/it]

[I 2026-03-10 22:03:28,862] Trial 7 finished with value: -0.9770492247885529 and parameters: {'n_estimators': 4924, 'learning_rate': 0.026000059117302653, 'max_depth': 6, 'min_child_weight': 3.6775602745204905, 'subsample': 0.9010984903770198, 'colsample_bytree': 0.5372753218398854, 'reg_lambda': 43.38624983446471, 'gamma': 7.722447692966574, 'reg_alpha': 5.35330210833913e-07}. Best is trial 6 with value: -0.9736448725391161.

Best trial: 6. Best value: -0.973645:  15%|█▌        | 9/60 [01:14<05:54,  6.96s/it]

[I 2026-03-10 22:03:31,272] Trial 8 finished with value: -0.9821352885793384 and parameters: {'n_estimators': 1060, 'learning_rate': 0.1601531217136121, 'max_depth': 8, 'min_child_weight': 14.851136192778759, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.5370223258670452, 'reg_lambda': 0.04835258599682954, 'gamma': 1.1586905952512971, 'reg_alpha': 0.32218907673802705}. Best is trial 6 with value: -0.9736448725391161.

Best trial: 6. Best value: -0.973645:  17%|█▋        | 10/60 [01:25<06:52,  8.24s/it]

[I 2026-03-10 22:03:42,389] Trial 9 finished with value: -0.9750049562627708 and parameters: {'n_estimators': 7856, 'learning_rate': 0.030816017044468066, 'max_depth': 2, 'min_child_weight': 6.908664112597582, 'subsample': 0.6625916610133735, 'colsample_bytree': 0.864803089169032, 'reg_lambda': 0.9905204218383901, 'gamma': 8.872127425763265, 'reg_alpha': 0.00012816913980027156}. Best is trial 6 with value: -0.9736448725391161.

Best trial: 6. Best value: -0.973645:  18%|█▊        | 11/60 [01:28<05:25,  6.63s/it]

[I 2026-03-10 22:03:45,377] Trial 10 finished with value: -0.9749422478132473 and parameters: {'n_estimators': 11489, 'learning_rate': 0.10417088978859979, 'max_depth': 4, 'min_child_weight': 1.34127563668158, 'subsample': 0.7828065453407016, 'colsample_bytree': 0.6808837830192477, 'reg_lambda': 0.018106433958753353, 'gamma': 3.924528921026324, 'reg_alpha': 0.006591030967925392}. Best is trial 6 with value: -0.9736448725391161.

Best trial: 6. Best value: -0.973645:  20%|██        | 12/60 [01:30<04:11,  5.23s/it]

[I 2026-03-10 22:03:47,398] Trial 11 finished with value: -0.9777111841672627 and parameters: {'n_estimators': 10125, 'learning_rate': 0.2923054009644287, 'max_depth': 10, 'min_child_weight': 18.51589588264785, 'subsample': 0.5156896024754595, 'colsample_bytree': 0.6362066546548342, 'reg_lambda': 0.013429680269363501, 'gamma': 3.111526195286856, 'reg_alpha': 9.909057816762803e-05}. Best is trial 6 with value: -0.9736448725391161.

Best trial: 6. Best value: -0.973645:  22%|██▏       | 13/60 [01:40<05:11,  6.62s/it]

[I 2026-03-10 22:03:57,226] Trial 12 finished with value: -0.9786995620866412 and parameters: {'n_estimators': 8880, 'learning_rate': 0.0122839419962954, 'max_depth': 10, 'min_child_weight': 19.974521139096183, 'subsample': 0.7343526094439211, 'colsample_bytree': 0.7921336951296047, 'reg_lambda': 0.007136981691829091, 'gamma': 1.040286131020716, 'reg_alpha': 2.8076480598129594}. Best is trial 6 with value: -0.9736448725391161.

Best trial: 13. Best value: -0.973294:  23%|██▎       | 14/60 [01:45<04:36,  6.01s/it]

[I 2026-03-10 22:04:01,824] Trial 13 finished with value: -0.97329421442981 and parameters: {'n_estimators': 10157, 'learning_rate': 0.051098201253078505, 'max_depth': 4, 'min_child_weight': 16.19852845573252, 'subsample': 0.5013757785563149, 'colsample_bytree': 0.6223441463224711, 'reg_lambda': 0.38697523652192395, 'gamma': 5.2498997564890715, 'reg_alpha': 0.009187218047421591}. Best is trial 13 with value: -0.97329421442981.

Best trial: 13. Best value: -0.973294:  25%|██▌       | 15/60 [01:50<04:14,  5.66s/it]

[I 2026-03-10 22:04:06,658] Trial 14 finished with value: -0.9735939723914873 and parameters: {'n_estimators': 11747, 'learning_rate': 0.05605945113063423, 'max_depth': 4, 'min_child_weight': 7.854098403005041, 'subsample': 0.5140230656274163, 'colsample_bytree': 0.756165400025059, 'reg_lambda': 0.48082269141529865, 'gamma': 6.29540378885119, 'reg_alpha': 0.01988842798453708}. Best is trial 13 with value: -0.97329421442981.

Best trial: 13. Best value: -0.973294:  27%|██▋       | 16/60 [01:55<04:08,  5.64s/it]

[I 2026-03-10 22:04:12,271] Trial 15 finished with value: -0.9741108748017238 and parameters: {'n_estimators': 11836, 'learning_rate': 0.0583762271222965, 'max_depth': 4, 'min_child_weight': 8.377142816778003, 'subsample': 0.724274028445038, 'colsample_bytree': 0.7714270006855597, 'reg_lambda': 0.7643561424808978, 'gamma': 6.092599562105124, 'reg_alpha': 0.023635307429998004}. Best is trial 13 with value: -0.97329421442981.

Best trial: 13. Best value: -0.973294:  28%|██▊       | 17/60 [02:00<03:50,  5.36s/it]

[I 2026-03-10 22:04:16,981] Trial 16 finished with value: -0.9733402739621058 and parameters: {'n_estimators': 10598, 'learning_rate': 0.04353837849838075, 'max_depth': 4, 'min_child_weight': 14.72230031943193, 'subsample': 0.5019126804032951, 'colsample_bytree': 0.8754986180062628, 'reg_lambda': 0.4147273141848499, 'gamma': 5.873196021519129, 'reg_alpha': 1.3021037527817063e-08}. Best is trial 13 with value: -0.97329421442981.

Best trial: 13. Best value: -0.973294:  30%|███       | 18/60 [02:06<03:56,  5.63s/it]

[I 2026-03-10 22:04:23,238] Trial 17 finished with value: -0.9752196780634174 and parameters: {'n_estimators': 10137, 'learning_rate': 0.044088914536090165, 'max_depth': 5, 'min_child_weight': 14.981579192787958, 'subsample': 0.8132394567758081, 'colsample_bytree': 0.9095923350290245, 'reg_lambda': 6.682392888700505, 'gamma': 5.559269301946996, 'reg_alpha': 1.8933920715019438e-08}. Best is trial 13 with value: -0.97329421442981.

Best trial: 13. Best value: -0.973294:  32%|███▏      | 19/60 [02:10<03:24,  4.98s/it]

[I 2026-03-10 22:04:26,688] Trial 18 finished with value: -0.9735953453106279 and parameters: {'n_estimators': 9778, 'learning_rate': 0.0969193339743378, 'max_depth': 3, 'min_child_weight': 14.802687725086756, 'subsample': 0.6614447990100766, 'colsample_bytree': 0.8662443061033537, 'reg_lambda': 2.566283524475542, 'gamma': 4.607551042630673, 'reg_alpha': 1.3522820124573307e-05}. Best is trial 13 with value: -0.97329421442981.

Best trial: 13. Best value: -0.973294:  33%|███▎      | 20/60 [02:18<03:55,  5.88s/it]

[I 2026-03-10 22:04:34,683] Trial 19 finished with value: -0.9762088074683198 and parameters: {'n_estimators': 3450, 'learning_rate': 0.04140156986237875, 'max_depth': 5, 'min_child_weight': 16.731150573718296, 'subsample': 0.9390932152220437, 'colsample_bytree': 0.9946520922146646, 'reg_lambda': 0.2193059760478956, 'gamma': 6.694947462225654, 'reg_alpha': 2.383208707094935e-08}. Best is trial 13 with value: -0.97329421442981.

Best trial: 13. Best value: -0.973294:  35%|███▌      | 21/60 [02:27<04:29,  6.90s/it]

[I 2026-03-10 22:04:43,971] Trial 20 finished with value: -0.9765841807763156 and parameters: {'n_estimators': 10810, 'learning_rate': 0.01859384693864264, 'max_depth': 3, 'min_child_weight': 13.639224917816454, 'subsample': 0.9933384010312033, 'colsample_bytree': 0.8303832977969607, 'reg_lambda': 1.6314702801564251, 'gamma': 5.05299159154377, 'reg_alpha': 1.2100777792849913e-05}. Best is trial 13 with value: -0.97329421442981.

Best trial: 21. Best value: -0.973273:  37%|███▋      | 22/60 [02:32<04:04,  6.44s/it]

[I 2026-03-10 22:04:49,321] Trial 21 finished with value: -0.9732726299843757 and parameters: {'n_estimators': 11350, 'learning_rate': 0.05549060910780199, 'max_depth': 4, 'min_child_weight': 10.300270266700965, 'subsample': 0.5002817187477304, 'colsample_bytree': 0.7367717140330564, 'reg_lambda': 0.42764927871589603, 'gamma': 6.612618554756145, 'reg_alpha': 0.007872812427279623}. Best is trial 21 with value: -0.9732726299843757.

Best trial: 21. Best value: -0.973273:  38%|███▊      | 23/60 [02:37<03:33,  5.76s/it]

[I 2026-03-10 22:04:53,501] Trial 22 finished with value: -0.9734726331798615 and parameters: {'n_estimators': 9504, 'learning_rate': 0.07389815136408183, 'max_depth': 5, 'min_child_weight': 10.469599160114512, 'subsample': 0.5062479311190433, 'colsample_bytree': 0.7223890956448988, 'reg_lambda': 0.386000071873563, 'gamma': 7.179939586243437, 'reg_alpha': 0.004666740275360322}. Best is trial 21 with value: -0.9732726299843757.

Best trial: 21. Best value: -0.973273:  40%|████      | 24/60 [02:41<03:07,  5.20s/it]

[I 2026-03-10 22:04:57,407] Trial 23 finished with value: -0.9737683219388066 and parameters: {'n_estimators': 10792, 'learning_rate': 0.03991229583075265, 'max_depth': 3, 'min_child_weight': 16.75070120426861, 'subsample': 0.5497087518158338, 'colsample_bytree': 0.6079489064735175, 'reg_lambda': 0.10958429123842792, 'gamma': 4.483527824525064, 'reg_alpha': 0.0005985680089192026}. Best is trial 21 with value: -0.9732726299843757.

Best trial: 21. Best value: -0.973273:  42%|████▏     | 25/60 [02:44<02:39,  4.57s/it]

[I 2026-03-10 22:05:00,491] Trial 24 finished with value: -0.9736303276878011 and parameters: {'n_estimators': 10861, 'learning_rate': 0.11974955040541294, 'max_depth': 4, 'min_child_weight': 18.295392432100595, 'subsample': 0.636379152915172, 'colsample_bytree': 0.90807494557577, 'reg_lambda': 9.306993993833979, 'gamma': 5.657582523217976, 'reg_alpha': 0.02816426972475697}. Best is trial 21 with value: -0.9732726299843757.

Best trial: 21. Best value: -0.973273:  43%|████▎     | 26/60 [02:54<03:35,  6.34s/it]

[I 2026-03-10 22:05:10,967] Trial 25 finished with value: -0.9742734019987445 and parameters: {'n_estimators': 11990, 'learning_rate': 0.020157156594215766, 'max_depth': 5, 'min_child_weight': 10.09219553074917, 'subsample': 0.5465375191711951, 'colsample_bytree': 0.7279519291867851, 'reg_lambda': 0.3168489227364299, 'gamma': 7.118146491680893, 'reg_alpha': 2.37286944953307e-05}. Best is trial 21 with value: -0.9732726299843757.

Best trial: 21. Best value: -0.973273:  45%|████▌     | 27/60 [02:57<02:54,  5.29s/it]

[I 2026-03-10 22:05:13,807] Trial 26 finished with value: -0.9742915467449678 and parameters: {'n_estimators': 7201, 'learning_rate': 0.06849722669146337, 'max_depth': 3, 'min_child_weight': 13.210123825397908, 'subsample': 0.6928851825031762, 'colsample_bytree': 0.818498051706648, 'reg_lambda': 0.9519036783170025, 'gamma': 3.8757626299426224, 'reg_alpha': 0.002202548338058537}. Best is trial 21 with value: -0.9732726299843757.

Best trial: 21. Best value: -0.973273:  47%|████▋     | 28/60 [03:01<02:42,  5.06s/it]

[I 2026-03-10 22:05:18,344] Trial 27 finished with value: -0.9733953485267982 and parameters: {'n_estimators': 9045, 'learning_rate': 0.04600258294819195, 'max_depth': 6, 'min_child_weight': 11.658809368901888, 'subsample': 0.5001613409633038, 'colsample_bytree': 0.6374682793952117, 'reg_lambda': 1.9672737862085345, 'gamma': 5.4239246271992405, 'reg_alpha': 1.4995171970643663e-07}. Best is trial 21 with value: -0.9732726299843757.

Best trial: 21. Best value: -0.973273:  48%|████▊     | 29/60 [03:10<03:09,  6.11s/it]

[I 2026-03-10 22:05:26,891] Trial 28 finished with value: -0.9751760875029929 and parameters: {'n_estimators': 10802, 'learning_rate': 0.034385556340785106, 'max_depth': 4, 'min_child_weight': 13.861976101296037, 'subsample': 0.6167841612549335, 'colsample_bytree': 0.9317340258861401, 'reg_lambda': 0.061878642639701976, 'gamma': 8.15981592450115, 'reg_alpha': 1.0742209681311488}. Best is trial 21 with value: -0.9732726299843757.

Best trial: 21. Best value: -0.973273:  50%|█████     | 30/60 [03:16<03:05,  6.18s/it]

[I 2026-03-10 22:05:33,242] Trial 29 finished with value: -0.9772076868623658 and parameters: {'n_estimators': 10054, 'learning_rate': 0.02093390088745139, 'max_depth': 7, 'min_child_weight': 16.048583489660075, 'subsample': 0.5552316644739163, 'colsample_bytree': 0.6983112477903436, 'reg_lambda': 0.15649617033896265, 'gamma': 0.1034843896909674, 'reg_alpha': 0.0016652517071094285}. Best is trial 21 with value: -0.9732726299843757.

Best trial: 21. Best value: -0.973273:  52%|█████▏    | 31/60 [03:20<02:33,  5.30s/it]

[I 2026-03-10 22:05:36,485] Trial 30 finished with value: -0.9744370641255771 and parameters: {'n_estimators': 11146, 'learning_rate': 0.08783014826148577, 'max_depth': 3, 'min_child_weight': 18.319700111005407, 'subsample': 0.5684611561691745, 'colsample_bytree': 0.5711519900998808, 'reg_lambda': 0.5459273736833353, 'gamma': 6.621935630012298, 'reg_alpha': 0.0735304059615949}. Best is trial 21 with value: -0.9732726299843757.

Best trial: 31. Best value: -0.973153:  53%|█████▎    | 32/60 [03:24<02:21,  5.07s/it]

[I 2026-03-10 22:05:41,022] Trial 31 finished with value: -0.9731528451475345 and parameters: {'n_estimators': 9083, 'learning_rate': 0.048859806078489276, 'max_depth': 6, 'min_child_weight': 11.844977727687894, 'subsample': 0.529502090787059, 'colsample_bytree': 0.6221891519862673, 'reg_lambda': 1.25044688974236, 'gamma': 5.395121626410534, 'reg_alpha': 8.328201421165654e-08}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  55%|█████▌    | 33/60 [03:30<02:26,  5.43s/it]

[I 2026-03-10 22:05:47,294] Trial 32 finished with value: -0.9732609824357242 and parameters: {'n_estimators': 9418, 'learning_rate': 0.05097613627215328, 'max_depth': 7, 'min_child_weight': 11.471027665601467, 'subsample': 0.5335107379851346, 'colsample_bytree': 0.5799483823494903, 'reg_lambda': 3.665772680677511, 'gamma': 5.929634540004731, 'reg_alpha': 1.00127473100463e-07}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  57%|█████▋    | 34/60 [03:35<02:12,  5.10s/it]

[I 2026-03-10 22:05:51,605] Trial 33 finished with value: -0.9733027800474906 and parameters: {'n_estimators': 8388, 'learning_rate': 0.06119353451816395, 'max_depth': 8, 'min_child_weight': 6.311586806377499, 'subsample': 0.6161908268434322, 'colsample_bytree': 0.5690495824790658, 'reg_lambda': 15.047685109489258, 'gamma': 4.6976962166944585, 'reg_alpha': 1.195066522830076e-07}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  58%|█████▊    | 35/60 [03:38<01:52,  4.51s/it]

[I 2026-03-10 22:05:54,761] Trial 34 finished with value: -0.973953498320871 and parameters: {'n_estimators': 9427, 'learning_rate': 0.05070792188457999, 'max_depth': 7, 'min_child_weight': 11.882122930187355, 'subsample': 0.5414695129613805, 'colsample_bytree': 0.6067254356519395, 'reg_lambda': 3.5150305092210643, 'gamma': 3.8196520948526893, 'reg_alpha': 2.390893166167022e-06}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  60%|██████    | 36/60 [03:47<02:22,  5.96s/it]

[I 2026-03-10 22:06:04,086] Trial 35 finished with value: -0.9739295380495576 and parameters: {'n_estimators': 6450, 'learning_rate': 0.035478213896365664, 'max_depth': 7, 'min_child_weight': 8.740985729136174, 'subsample': 0.5813712261302015, 'colsample_bytree': 0.6405945324376946, 'reg_lambda': 1.7745886305185314, 'gamma': 7.272582014961714, 'reg_alpha': 0.0005032239202724504}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  62%|██████▏   | 37/60 [03:52<02:07,  5.52s/it]

[I 2026-03-10 22:06:08,599] Trial 36 finished with value: -0.9744544297421349 and parameters: {'n_estimators': 8459, 'learning_rate': 0.13011311953101826, 'max_depth': 9, 'min_child_weight': 10.632395105278139, 'subsample': 0.5995773398650043, 'colsample_bytree': 0.5973035875758118, 'reg_lambda': 5.771113434097904, 'gamma': 8.287931271359861, 'reg_alpha': 6.030018123026393e-08}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  63%|██████▎   | 38/60 [03:56<01:52,  5.11s/it]

[I 2026-03-10 22:06:12,753] Trial 37 finished with value: -0.973738884278661 and parameters: {'n_estimators': 9216, 'learning_rate': 0.08470407873727397, 'max_depth': 6, 'min_child_weight': 12.38163097764722, 'subsample': 0.534790250755425, 'colsample_bytree': 0.5562855425520193, 'reg_lambda': 17.31044643835647, 'gamma': 5.1728022310116994, 'reg_alpha': 6.146206319605973e-07}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  65%|██████▌   | 39/60 [04:06<02:20,  6.70s/it]

[I 2026-03-10 22:06:23,150] Trial 38 finished with value: -0.9735418128810794 and parameters: {'n_estimators': 6115, 'learning_rate': 0.024412638843396433, 'max_depth': 9, 'min_child_weight': 9.538606189831068, 'subsample': 0.5683916232096065, 'colsample_bytree': 0.5199633310391094, 'reg_lambda': 0.9943034852646726, 'gamma': 6.2867143201668805, 'reg_alpha': 4.476604111626914e-06}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  67%|██████▋   | 40/60 [04:09<01:49,  5.49s/it]

[I 2026-03-10 22:06:25,815] Trial 39 finished with value: -0.9750432932329026 and parameters: {'n_estimators': 7079, 'learning_rate': 0.06336021878282277, 'max_depth': 5, 'min_child_weight': 11.259283694811874, 'subsample': 0.5889792260681813, 'colsample_bytree': 0.5056820332121027, 'reg_lambda': 0.19644349155483942, 'gamma': 2.466438414053062, 'reg_alpha': 5.1776680961251085e-05}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  68%|██████▊   | 41/60 [04:13<01:33,  4.93s/it]

[I 2026-03-10 22:06:29,431] Trial 40 finished with value: -0.9738606267329075 and parameters: {'n_estimators': 7978, 'learning_rate': 0.16941292768795144, 'max_depth': 6, 'min_child_weight': 6.11316227904604, 'subsample': 0.5318754933738227, 'colsample_bytree': 0.6585624831906014, 'reg_lambda': 0.10507945634604036, 'gamma': 6.751376841209982, 'reg_alpha': 5.785821786686213e-07}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  70%|███████   | 42/60 [04:17<01:26,  4.79s/it]

[I 2026-03-10 22:06:33,892] Trial 41 finished with value: -0.9733880706439019 and parameters: {'n_estimators': 8415, 'learning_rate': 0.050766905037667454, 'max_depth': 8, 'min_child_weight': 5.457146934550939, 'subsample': 0.6159018509115495, 'colsample_bytree': 0.5752560632733698, 'reg_lambda': 11.691115375561738, 'gamma': 4.632837707723702, 'reg_alpha': 1.3014957564729496e-07}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  72%|███████▏  | 43/60 [04:23<01:26,  5.10s/it]

[I 2026-03-10 22:06:39,709] Trial 42 finished with value: -0.9737645888261908 and parameters: {'n_estimators': 10209, 'learning_rate': 0.06122204423670645, 'max_depth': 7, 'min_child_weight': 7.528243869646966, 'subsample': 0.5312874849228704, 'colsample_bytree': 0.5535396101708218, 'reg_lambda': 30.0279427014444, 'gamma': 4.551130741463596, 'reg_alpha': 7.964661734404748e-08}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  73%|███████▎  | 44/60 [04:28<01:20,  5.05s/it]

[I 2026-03-10 22:06:44,662] Trial 43 finished with value: -0.9736978433856397 and parameters: {'n_estimators': 8652, 'learning_rate': 0.03507645979363265, 'max_depth': 8, 'min_child_weight': 1.7797217260408589, 'subsample': 0.6243532258025263, 'colsample_bytree': 0.6180929039971372, 'reg_lambda': 14.536010916395513, 'gamma': 3.5202809771847035, 'reg_alpha': 2.9482447517969033e-07}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  75%|███████▌  | 45/60 [04:32<01:11,  4.77s/it]

[I 2026-03-10 22:06:48,770] Trial 44 finished with value: -0.9735020627893896 and parameters: {'n_estimators': 11310, 'learning_rate': 0.07567513295872053, 'max_depth': 7, 'min_child_weight': 3.013978417110923, 'subsample': 0.5655437183504385, 'colsample_bytree': 0.6940909776518457, 'reg_lambda': 3.3524540435268646, 'gamma': 4.958355271348339, 'reg_alpha': 2.3068670290092255e-06}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  77%|███████▋  | 46/60 [04:38<01:11,  5.13s/it]

[I 2026-03-10 22:06:54,736] Trial 45 finished with value: -0.9734768991392665 and parameters: {'n_estimators': 7702, 'learning_rate': 0.053239619695115065, 'max_depth': 9, 'min_child_weight': 13.018855952171002, 'subsample': 0.524808807156216, 'colsample_bytree': 0.580789146392872, 'reg_lambda': 1.2993309029014048, 'gamma': 5.950603353450806, 'reg_alpha': 2.8821163112862656e-08}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  78%|███████▊  | 47/60 [04:44<01:10,  5.41s/it]

[I 2026-03-10 22:07:00,815] Trial 46 finished with value: -0.974588266420352 and parameters: {'n_estimators': 9644, 'learning_rate': 0.03047109489815701, 'max_depth': 8, 'min_child_weight': 9.188609533517814, 'subsample': 0.6876589268004705, 'colsample_bytree': 0.6647781515677791, 'reg_lambda': 20.36411506747313, 'gamma': 4.232180390003573, 'reg_alpha': 0.008005546396676125}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  80%|████████  | 48/60 [04:48<00:59,  4.98s/it]

[I 2026-03-10 22:07:04,769] Trial 47 finished with value: -0.9762459765781617 and parameters: {'n_estimators': 1528, 'learning_rate': 0.03757978134208835, 'max_depth': 9, 'min_child_weight': 6.8705740358321155, 'subsample': 0.776950576099445, 'colsample_bytree': 0.6239477523417604, 'reg_lambda': 5.473625557831662, 'gamma': 2.2192860944611894, 'reg_alpha': 0.07460006293066786}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  82%|████████▏ | 49/60 [04:51<00:47,  4.33s/it]

[I 2026-03-10 22:07:07,581] Trial 48 finished with value: -0.9734837552288175 and parameters: {'n_estimators': 5388, 'learning_rate': 0.04739866476150952, 'max_depth': 2, 'min_child_weight': 4.574387067825544, 'subsample': 0.5974648614222792, 'colsample_bytree': 0.5492586425366298, 'reg_lambda': 0.5995670354195527, 'gamma': 3.324102182560876, 'reg_alpha': 4.834434680617716e-08}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  83%|████████▎ | 50/60 [04:57<00:49,  4.95s/it]

[I 2026-03-10 22:07:13,990] Trial 49 finished with value: -0.9753364691550847 and parameters: {'n_estimators': 10341, 'learning_rate': 0.06574151486070576, 'max_depth': 7, 'min_child_weight': 10.955983478459334, 'subsample': 0.521785993957634, 'colsample_bytree': 0.5954373088086702, 'reg_lambda': 45.300729221002335, 'gamma': 7.505209854308419, 'reg_alpha': 2.1015882194868255e-07}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  85%|████████▌ | 51/60 [05:01<00:41,  4.60s/it]

[I 2026-03-10 22:07:17,770] Trial 50 finished with value: -0.9750328384832821 and parameters: {'n_estimators': 8943, 'learning_rate': 0.08202371511849324, 'max_depth': 5, 'min_child_weight': 15.829632632990434, 'subsample': 0.8376667760959206, 'colsample_bytree': 0.6796691969829426, 'reg_lambda': 0.04174128898607536, 'gamma': 5.216418501012187, 'reg_alpha': 0.24018915693832604}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  87%|████████▋ | 52/60 [05:07<00:41,  5.17s/it]

[I 2026-03-10 22:07:24,285] Trial 51 finished with value: -0.9734197844456352 and parameters: {'n_estimators': 10549, 'learning_rate': 0.04318179294902425, 'max_depth': 4, 'min_child_weight': 14.78634886972056, 'subsample': 0.5147945159969333, 'colsample_bytree': 0.7163336861319978, 'reg_lambda': 0.3593721544142674, 'gamma': 5.971800361860766, 'reg_alpha': 2.1784321097779202e-08}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  88%|████████▊ | 53/60 [05:12<00:34,  4.95s/it]

[I 2026-03-10 22:07:28,702] Trial 52 finished with value: -0.9733210332338942 and parameters: {'n_estimators': 9952, 'learning_rate': 0.05555832768928094, 'max_depth': 4, 'min_child_weight': 14.040937894534666, 'subsample': 0.5046871862103329, 'colsample_bytree': 0.9682636541517252, 'reg_lambda': 0.2768575060262616, 'gamma': 5.596960529394063, 'reg_alpha': 8.439823933568173e-07}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  90%|█████████ | 54/60 [05:17<00:29,  4.93s/it]

[I 2026-03-10 22:07:33,597] Trial 53 finished with value: -0.9739335578281135 and parameters: {'n_estimators': 11438, 'learning_rate': 0.05726655969795052, 'max_depth': 8, 'min_child_weight': 13.830620181538617, 'subsample': 0.5524925074250343, 'colsample_bytree': 0.5314065839402677, 'reg_lambda': 0.0036769230950141475, 'gamma': 6.329139475915017, 'reg_alpha': 4.34781248054276e-07}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  92%|█████████▏| 55/60 [05:21<00:24,  4.82s/it]

[I 2026-03-10 22:07:38,149] Trial 54 finished with value: -0.9732760533978058 and parameters: {'n_estimators': 9781, 'learning_rate': 0.06960675586048531, 'max_depth': 6, 'min_child_weight': 12.58354285020261, 'subsample': 0.5020882830448986, 'colsample_bytree': 0.9492170250239668, 'reg_lambda': 2.4113238895452196, 'gamma': 5.650606866635718, 'reg_alpha': 1.0652070947130028e-08}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  93%|█████████▎| 56/60 [05:24<00:16,  4.23s/it]

[I 2026-03-10 22:07:40,992] Trial 55 finished with value: -0.9734275559334943 and parameters: {'n_estimators': 8060, 'learning_rate': 0.10063253748898501, 'max_depth': 6, 'min_child_weight': 12.774985893195876, 'subsample': 0.5004007215841224, 'colsample_bytree': 0.8369177045668795, 'reg_lambda': 2.602690651315682, 'gamma': 5.005174755015352, 'reg_alpha': 1.0646648451875614e-08}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  95%|█████████▌| 57/60 [05:30<00:14,  4.72s/it]

[I 2026-03-10 22:07:46,852] Trial 56 finished with value: -0.9740557230984772 and parameters: {'n_estimators': 9324, 'learning_rate': 0.07125358635486105, 'max_depth': 6, 'min_child_weight': 9.854172335199904, 'subsample': 0.5821567335937818, 'colsample_bytree': 0.7986110253487979, 'reg_lambda': 1.2426133907691896, 'gamma': 6.846539835215122, 'reg_alpha': 4.220871555908589e-08}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  97%|█████████▋| 58/60 [05:34<00:08,  4.42s/it]

[I 2026-03-10 22:07:50,574] Trial 57 finished with value: -0.9735798608555901 and parameters: {'n_estimators': 7253, 'learning_rate': 0.09286372813412667, 'max_depth': 7, 'min_child_weight': 19.509241903594475, 'subsample': 0.6473542067286296, 'colsample_bytree': 0.7696531224629275, 'reg_lambda': 8.95304108333115, 'gamma': 4.79699656397865, 'reg_alpha': 0.0002336272171457802}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153:  98%|█████████▊| 59/60 [05:37<00:04,  4.18s/it]

[I 2026-03-10 22:07:54,190] Trial 58 finished with value: -0.973169372110837 and parameters: {'n_estimators': 9566, 'learning_rate': 0.11144596455645012, 'max_depth': 5, 'min_child_weight': 12.250442979946222, 'subsample': 0.542692378169743, 'colsample_bytree': 0.6586952598043216, 'reg_lambda': 4.018915218319795, 'gamma': 4.161348230879215, 'reg_alpha': 1.0134157635121823e-07}. Best is trial 31 with value: -0.9731528451475345.

Best trial: 31. Best value: -0.973153: 100%|██████████| 60/60 [05:41<00:00,  5.69s/it]

[I 2026-03-10 22:07:57,751] Trial 59 finished with value: -0.9731970916802476 and parameters: {'n_estimators': 9809, 'learning_rate': 0.11171719434951391, 'max_depth': 5, 'min_child_weight': 11.813987263729464, 'subsample': 0.5426252576217455, 'colsample_bytree': 0.7420092233402981, 'reg_lambda': 0.7006375272894638, 'gamma': 5.538791204961851, 'reg_alpha': 0.015253269997023897}. Best is trial 31 with value: -0.9731528451475345.

Best CV neg_log_loss: -0.9731528451475345
Best params:
 {'n_estimators': 9083, 'learning_rate': 0.048859806078489276, 'max_depth': 6, 'min_child_weight': 11.844977727687894, 'subsample': 0.529502090787059, 'colsample_bytree': 0.6221891519862673, 'reg_lambda': 1.25044688974236, 'gamma': 5.395121626410534, 'reg_alpha': 8.328201421165654e-08}
[0]	validation_0-mlogloss:1.06725

[100]	validation_0-mlogloss:0.97638
[200]	validation_0-mlogloss:0.97633
[300]	validation_0-mlogloss:0.97648
[400]	validation_0-mlogloss:0.97691
[421]	validation_0-mlogloss:0.97727

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.6221891519862673, device=None,
              early_stopping_rounds=200, enable_categorical=False,
              eval_metric='mlogloss', feature_types=None, feature_weights=None,
              gamma=5.395121626410534, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.048859806078489276,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=11.844977727687894, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=9083,
              n_jobs=-1, num_class=3, ...)

In [51]:
# metrics
proba_xgb_o = model_xgb_opt.predict_proba(X_test)
pred_xgb_o = proba_xgb_o.argmax(axis=1)

print("\nAccuracy:", accuracy_score(y_test, pred_xgb_o))
print("LogLoss:", log_loss(y_test, proba_xgb_o))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_xgb_o))
print("\nClassification Report:\n", classification_report(y_test, pred_xgb_o, digits=3))

Accuracy: 0.5370070232306862
LogLoss: 0.9760681872934279

Confusion Matrix:
 [[646   0 153]
 [270   0 157]
 [277   0 348]]

Classification Report:
               precision    recall  f1-score   support

           0      0.541     0.809     0.649       799
           1      0.000     0.000     0.000       427
           2      0.529     0.557     0.542       625

    accuracy                          0.537      1851
   macro avg      0.357     0.455     0.397      1851
weighted avg      0.412     0.537     0.463      1851

c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [ ]:
proba_xgb_opt_rng = model_xgb_opt.predict_proba(X_test)

rng_xgbo = np.random.default_rng(42)

pred_xgb_opt_rng = np.array([
    rng.choice(len(p), p=p) for p in proba_xgb_opt_rng
])

In [ ]:
print("TEST Accuracy:", accuracy_score(y_test, pred_xgb_opt_rng))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_xgb_opt_rng))
print("\nClassification Report:\n", classification_report(y_test, pred_xgb_opt_rng, digits=3))

TEST Accuracy: 0.41707185305240413

Confusion Matrix:
 [[424 189 186]
 [198  98 131]
 [220 155 250]]

Classification Report:
               precision    recall  f1-score   support

           0      0.504     0.531     0.517       799
           1      0.222     0.230     0.226       427
           2      0.441     0.400     0.419       625

    accuracy                          0.417      1851
   macro avg      0.389     0.387     0.387      1851
weighted avg      0.417     0.417     0.417      1851

In [54]:
X_xgbo_last = X_test.iloc[[-1]]   # double brackets keep it 2D

pred_xgbo_last = model_xgb_opt.predict(X_xgb_last)
proba_xgbo_last = model_xgb_opt.predict_proba(X_xgbo_last)

print("Predicted class:", pred_xgbo_last)
print("Probabilities:", proba_xgbo_last)

Predicted class: [2]
Probabilities: [[0.31230244 0.25607124 0.4316263 ]]

In [57]:
proba_xgbo_df = pd.DataFrame(proba_xgb_o, columns=['pred_xgbo_H', 'pred_xgbo_D', 'pred_xgbo_A'])
proba_xgbo_df = pd.concat([proba_xgbo_df.reset_index(drop=True), Features_odds], axis=1)
proba_xgbo_df

      pred_xgbo_H  pred_xgbo_D  pred_xgbo_A  HomeOdds  DrawOdds  AwayOdds
0        0.244796     0.243381     0.511823  0.200669  0.235097  0.564234
1        0.525195     0.262130     0.212675  0.454605  0.288920  0.256475
2        0.385678     0.281044     0.333278  0.357701  0.294966  0.347333
3        0.537035     0.260826     0.202140  0.591714  0.228777  0.179509
4        0.581199     0.254216     0.164585  0.507399  0.251043  0.241558
...           ...          ...          ...       ...       ...       ...
1846     0.296046     0.253873     0.450081  0.309101  0.256753  0.434146
1847     0.151303     0.159296     0.689401  0.100538  0.162964  0.736498
1848     0.729224     0.162378     0.108398  0.721382  0.170040  0.108578
1849     0.654974     0.208057     0.136969  0.679776  0.168440  0.151784
1850     0.312302     0.256071     0.431626  0.352613  0.254144  0.393243

[1851 rows x 6 columns]