Libaries/Tools

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
import sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix, classification_report
import optuna
from sklearn.model_selection import StratifiedKFold, cross_val_score

c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

LOAD DATASET

In [2]:
#dataset
matches = pd.read_csv('C:/Users/mikko/OneDrive/python_projektit/ML_dec_tree_football/data_csv/Matches.csv')

C:\Users\mikko\AppData\Local\Temp\ipykernel_24156\583763451.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  matches = pd.read_csv('C:/Users/mikko/OneDrive/python_projektit/ML_dec_tree_football/data_csv/Matches.csv')

DROP COLUMNS AND FILL_EMPTY

In [3]:
matches_cleaned = matches.drop(columns=['MatchTime', 'HomeFouls', 'AwayFouls',
    'HomeYellow', 'AwayYellow', 'HomeRed', 'AwayRed',
    'MaxHome', 'MaxDraw', 'MaxAway',
    'Over25', 'Under25', 'MaxOver25', 'MaxUnder25',
    'HandiSize', 'HandiHome', 'HandiAway',
    'C_LTH', 'C_LTA', 'C_VHD', 'C_VAD',
    'C_HTB', 'C_PHB'
])

matches_cleaned = matches_cleaned.dropna()

FILTER AND REPLACE VALUES

In [4]:
matches_cleaned = matches_cleaned[matches_cleaned['Division'] == 'E0']
matches_cleaned['MatchDate'] = pd.to_datetime(matches_cleaned['MatchDate'])

matches_cleaned[['HomeTeam', 'AwayTeam']] = (
    matches_cleaned[['HomeTeam', 'AwayTeam']]
        .replace({
            "Nott'm Forest": "Nottingham Forest",
            "Nottm Forest": "Nottingham Forest"
        })
)

matches_cleaned['HomePoints'] = matches_cleaned['FTResult'].map({
    'H': 3,
    'D': 1,
    'A': 0
})

matches_cleaned['AwayPoints'] = matches_cleaned['FTResult'].map({
    'H': 0,
    'D': 1,
    'A': 3
})

matches_cleaned['FTResult'] = matches_cleaned['FTResult'].map({
    'H': 0,
    'D': 1,
    'A': 2
})

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

matches_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9325 entries, 154 to 230510
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Division     9325 non-null   object
 1   MatchDate    9325 non-null   datetime64[ns]
 2   HomeTeam     9325 non-null   object
 3   AwayTeam     9325 non-null   object
 4   HomeElo      9325 non-null   float64
 5   AwayElo      9325 non-null   float64
 6   Form3Home    9325 non-null   float64
 7   Form5Home    9325 non-null   float64
 8   Form3Away    9325 non-null   float64
 9   Form5Away    9325 non-null   float64
 10  FTHome       9325 non-null   float64
 11  FTAway       9325 non-null   float64
 12  FTResult     9325 non-null   int64
 13  HTHome       9325 non-null   float64
 14  HTAway       9325 non-null   float64
 15  HTResult     9325 non-null   object
 16  HomeShots    9325 non-null   float64
 17  AwayShots    9325 non-null   float64
 18  HomeTarget   9325 non-null   float64
 19  AwayTarget   9325 non-null   float64
 20  HomeCorners  9325 non-null   float64
 21  AwayCorners  9325 non-null   float64
 22  OddHome      9325 non-null   float64
 23  OddDraw      9325 non-null   float64
 24  OddAway      9325 non-null   float64
 25  HomePoints   9325 non-null   int64
 26  AwayPoints   9325 non-null   int64
dtypes: datetime64[ns](1), float64(19), int64(3), object(4)
memory usage: 2.0+ MB

In [6]:
matches_cleaned['margin'] = 1 / matches_cleaned['OddHome'] + 1 / matches_cleaned['OddDraw'] + 1 / matches_cleaned['OddAway']
matches_cleaned['HomeOdds'] = 1 / matches_cleaned['OddHome'] / matches_cleaned['margin']
matches_cleaned['DrawOdds'] = 1 / matches_cleaned['OddDraw'] / matches_cleaned['margin']
matches_cleaned['AwayOdds'] = 1 / matches_cleaned['OddAway'] / matches_cleaned['margin']

In [7]:
matches_cleaned = matches_cleaned.drop(columns=['OddHome', 'OddDraw', 'OddAway', 'margin'])

In [8]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

matches_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9325 entries, 154 to 230510
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Division     9325 non-null   object
 1   MatchDate    9325 non-null   datetime64[ns]
 2   HomeTeam     9325 non-null   object
 3   AwayTeam     9325 non-null   object
 4   HomeElo      9325 non-null   float64
 5   AwayElo      9325 non-null   float64
 6   Form3Home    9325 non-null   float64
 7   Form5Home    9325 non-null   float64
 8   Form3Away    9325 non-null   float64
 9   Form5Away    9325 non-null   float64
 10  FTHome       9325 non-null   float64
 11  FTAway       9325 non-null   float64
 12  FTResult     9325 non-null   int64
 13  HTHome       9325 non-null   float64
 14  HTAway       9325 non-null   float64
 15  HTResult     9325 non-null   object
 16  HomeShots    9325 non-null   float64
 17  AwayShots    9325 non-null   float64
 18  HomeTarget   9325 non-null   float64
 19  AwayTarget   9325 non-null   float64
 20  HomeCorners  9325 non-null   float64
 21  AwayCorners  9325 non-null   float64
 22  HomePoints   9325 non-null   int64
 23  AwayPoints   9325 non-null   int64
 24  HomeOdds     9325 non-null   float64
 25  DrawOdds     9325 non-null   float64
 26  AwayOdds     9325 non-null   float64
dtypes: datetime64[ns](1), float64(19), int64(3), object(4)
memory usage: 2.0+ MB

ROLLING AVERAGES FOR TOTAL POINTS

In [9]:
matches_cleaned['MatchDate'] = pd.to_datetime(matches_cleaned['MatchDate'])

# Sort chronologically and create stable match id
matches_cleaned = matches_cleaned.sort_values('MatchDate').reset_index(drop=True)
matches_cleaned['MatchID'] = matches_cleaned.index

# --- Long format: one row per (match, team) with points earned ---
home_long = matches_cleaned[['MatchID', 'MatchDate', 'HomeTeam', 'HomePoints']].copy()
home_long = home_long.rename(columns={'HomeTeam': 'Team', 'HomePoints': 'Points'})
home_long['Side'] = 'Home'

away_long = matches_cleaned[['MatchID', 'MatchDate', 'AwayTeam', 'AwayPoints']].copy()
away_long = away_long.rename(columns={'AwayTeam': 'Team', 'AwayPoints': 'Points'})
away_long['Side'] = 'Away'

teams_long = pd.concat([home_long, away_long], ignore_index=True)

# --- Rolling average points over last 20 games per team (BEFORE match) ---
teams_long = teams_long.sort_values(['Team', 'MatchDate', 'MatchID']).reset_index(drop=True)

g = teams_long.groupby('Team')['Points']

# rolling avg of previous 20 matches: shift to exclude current match
teams_long['RollingAvgPoints20Before'] = (
    g.apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
     .reset_index(level=0, drop=True)
)

# --- Merge back to match table as Home/Away features ---
home_feat = teams_long[teams_long['Side'] == 'Home'][['MatchID', 'RollingAvgPoints20Before']].rename(
    columns={'RollingAvgPoints20Before': 'HomeTotalPointsRoll20'}  # name kept, now rolling avg
)
away_feat = teams_long[teams_long['Side'] == 'Away'][['MatchID', 'RollingAvgPoints20Before']].rename(
    columns={'RollingAvgPoints20Before': 'AwayTotalPointsRoll20'}  # name kept, now rolling avg
)

matches_cleaned = matches_cleaned.merge(home_feat, on='MatchID', how='left')
matches_cleaned = matches_cleaned.merge(away_feat, on='MatchID', how='left')

ROLLING AVERAGES FOR HOME POINTS

In [10]:
# Ensure chronological order
matches_cleaned['MatchDate'] = pd.to_datetime(matches_cleaned['MatchDate'])
matches_cleaned = matches_cleaned.sort_values('MatchDate').reset_index(drop=True)

# --- Rolling avg of last 20 HOME matches for each team ---
matches_cleaned['HomeTeamHomePointsRolling20'] = (
    matches_cleaned
    .groupby('HomeTeam')['HomePoints']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

ROLLING AVERAGES FOR AWAY POINTS

In [11]:
matches_cleaned['AwayTeamAwayPointsRolling20'] = (
    matches_cleaned
    .groupby('AwayTeam')['AwayPoints']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

ROLLING AVERAGES FOR TOTAL SHOTS

In [12]:
# Ensure shots are numeric
matches_cleaned['HomeShots'] = pd.to_numeric(matches_cleaned['HomeShots'], errors='coerce')
matches_cleaned['AwayShots'] = pd.to_numeric(matches_cleaned['AwayShots'], errors='coerce')

# --- Long format: one row per (match, team) with shots taken in that match ---
home_long = matches_cleaned[['MatchID', 'MatchDate', 'HomeTeam', 'HomeShots']].copy()
home_long = home_long.rename(columns={'HomeTeam': 'Team', 'HomeShots': 'Shots'})
home_long['Side'] = 'Home'

away_long = matches_cleaned[['MatchID', 'MatchDate', 'AwayTeam', 'AwayShots']].copy()
away_long = away_long.rename(columns={'AwayTeam': 'Team', 'AwayShots': 'Shots'})
away_long['Side'] = 'Away'

teams_long = pd.concat([home_long, away_long], ignore_index=True)

# --- Rolling AVG shots per team over last 20 games (BEFORE match), no seasonality ---
teams_long = teams_long.sort_values(['Team', 'MatchDate', 'MatchID']).reset_index(drop=True)

g = teams_long.groupby('Team')['Shots']

teams_long['ShotsRolling20Before'] = (
    g.apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
     .reset_index(level=0, drop=True)
)

# --- Merge back to match table as Home/Away features ---
home_feat = teams_long[teams_long['Side'] == 'Home'][['MatchID', 'ShotsRolling20Before']].rename(
    columns={'ShotsRolling20Before': 'HomeTeamShotsRolling20'}
)
away_feat = teams_long[teams_long['Side'] == 'Away'][['MatchID', 'ShotsRolling20Before']].rename(
    columns={'ShotsRolling20Before': 'AwayTeamShotsRolling20'}
)

matches_cleaned = matches_cleaned.merge(home_feat, on='MatchID', how='left')
matches_cleaned = matches_cleaned.merge(away_feat, on='MatchID', how='left')
# Optional cleanup:
# matches_cleaned = matches_cleaned.drop(columns=['MatchID'])

ROLLING AVERAGE FOR HOME AND AWAY SHOTS

In [13]:
# Ensure datetime + chronological order
matches_cleaned['MatchDate'] = pd.to_datetime(matches_cleaned['MatchDate'])
matches_cleaned = matches_cleaned.sort_values('MatchDate').reset_index(drop=True)

# Shots numeric
matches_cleaned['HomeShots'] = pd.to_numeric(matches_cleaned['HomeShots'], errors='coerce')
matches_cleaned['AwayShots'] = pd.to_numeric(matches_cleaned['AwayShots'], errors='coerce')

# --- Home team: rolling avg of last 20 HOME matches (exclude current) ---
matches_cleaned['HomeTeamShotsHomeRolling20'] = (
    matches_cleaned
    .groupby('HomeTeam')['HomeShots']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

# --- Away team: rolling avg of last 20 AWAY matches (exclude current) ---
matches_cleaned['AwayTeamShotsAwayRolling20'] = (
    matches_cleaned
    .groupby('AwayTeam')['AwayShots']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

# Optional: fill early NaNs (teams with no prior home/away games)
# matches_cleaned[['HomeTeamShotsHomeRolling20', 'AwayTeamShotsAwayRolling20']] = (
#     matches_cleaned[['HomeTeamShotsHomeRolling20', 'AwayTeamShotsAwayRolling20']].fillna(0)
# )

ROLLING AVERAGE FOR SHOTS ON TARGET

In [14]:
# Ensure numeric
matches_cleaned['HomeTarget'] = pd.to_numeric(matches_cleaned['HomeTarget'], errors='coerce')
matches_cleaned['AwayTarget'] = pd.to_numeric(matches_cleaned['AwayTarget'], errors='coerce')

# Make sure sorted and MatchID exists
matches_cleaned['MatchDate'] = pd.to_datetime(matches_cleaned['MatchDate'])
matches_cleaned = matches_cleaned.sort_values('MatchDate').reset_index(drop=True)
if 'MatchID' not in matches_cleaned.columns:
    matches_cleaned['MatchID'] = matches_cleaned.index

# --- Long format ---
home_long = matches_cleaned[['MatchID','MatchDate','HomeTeam','HomeTarget']].copy()
home_long = home_long.rename(columns={'HomeTeam':'Team','HomeTarget':'TargetShots'})
home_long['Side'] = 'Home'

away_long = matches_cleaned[['MatchID','MatchDate','AwayTeam','AwayTarget']].copy()
away_long = away_long.rename(columns={'AwayTeam':'Team','AwayTarget':'TargetShots'})
away_long['Side'] = 'Away'

teams_long = pd.concat([home_long, away_long], ignore_index=True)

# --- Rolling AVG per team over last 20 matches (BEFORE match), no seasonality ---
teams_long = teams_long.sort_values(['Team','MatchDate','MatchID']).reset_index(drop=True)

g = teams_long.groupby('Team')['TargetShots']

teams_long['TargetShotsRolling20Before'] = (
    g.apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
     .reset_index(level=0, drop=True)
)

# --- Merge back ---
home_feat = teams_long[teams_long['Side']=='Home'][['MatchID','TargetShotsRolling20Before']] \
    .rename(columns={'TargetShotsRolling20Before':'HomeTeamTargetShotsRolling20'})

away_feat = teams_long[teams_long['Side']=='Away'][['MatchID','TargetShotsRolling20Before']] \
    .rename(columns={'TargetShotsRolling20Before':'AwayTeamTargetShotsRolling20'})

matches_cleaned = matches_cleaned.merge(home_feat, on='MatchID', how='left')
matches_cleaned = matches_cleaned.merge(away_feat, on='MatchID', how='left')

ROLLING AVERAGE TOTAL GOALS HOME AND AWAY TEAM

In [15]:
# Ensure numeric
matches_cleaned['FTHome'] = pd.to_numeric(matches_cleaned['FTHome'], errors='coerce')
matches_cleaned['FTAway'] = pd.to_numeric(matches_cleaned['FTAway'], errors='coerce')

# --- Long format: goals scored by each team in each match ---
home_long = matches_cleaned[['MatchID', 'MatchDate', 'HomeTeam', 'FTHome']].copy()
home_long = home_long.rename(columns={'HomeTeam': 'Team', 'FTHome': 'Goals'})
home_long['Side'] = 'Home'

away_long = matches_cleaned[['MatchID', 'MatchDate', 'AwayTeam', 'FTAway']].copy()
away_long = away_long.rename(columns={'AwayTeam': 'Team', 'FTAway': 'Goals'})
away_long['Side'] = 'Away'

teams_long = pd.concat([home_long, away_long], ignore_index=True)

# --- Rolling AVG goals per team over last 20 matches (BEFORE match), no seasonality ---
teams_long = teams_long.sort_values(['Team', 'MatchDate', 'MatchID']).reset_index(drop=True)

g = teams_long.groupby('Team')['Goals']

teams_long['GoalsRolling20Before'] = (
    g.apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
     .reset_index(level=0, drop=True)
)

# --- Merge back to match table ---
home_feat = teams_long[teams_long['Side'] == 'Home'][['MatchID', 'GoalsRolling20Before']].rename(
    columns={'GoalsRolling20Before': 'HomeTotalGoalsRolling20'}
)
away_feat = teams_long[teams_long['Side'] == 'Away'][['MatchID', 'GoalsRolling20Before']].rename(
    columns={'GoalsRolling20Before': 'AwayTotalGoalsRolling20'}
)

matches_cleaned = matches_cleaned.merge(home_feat, on='MatchID', how='left')
matches_cleaned = matches_cleaned.merge(away_feat, on='MatchID', how='left')

ROLLING AVERAGES GOALS HOME AND AWAY

In [16]:
# Ensure numeric
matches_cleaned['FTHome'] = pd.to_numeric(matches_cleaned['FTHome'], errors='coerce')
matches_cleaned['FTAway'] = pd.to_numeric(matches_cleaned['FTAway'], errors='coerce')

# --- Home team: rolling avg goals in last 20 HOME matches (exclude current) ---
matches_cleaned['HomeGoalsHomeRolling20'] = (
    matches_cleaned
    .groupby('HomeTeam')['FTHome']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

# --- Away team: rolling avg goals in last 20 AWAY matches (exclude current) ---
matches_cleaned['AwayGoalsAwayRolling20'] = (
    matches_cleaned
    .groupby('AwayTeam')['FTAway']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

# Optional: fill early NaNs
# matches_cleaned[['HomeGoalsHomeRolling20','AwayGoalsAwayRolling20']] = (
#     matches_cleaned[['HomeGoalsHomeRolling20','AwayGoalsAwayRolling20']].fillna(0)
# )

ROLLING AVERAGE GOALS CONCEDED HOME AND AWAY FOR HOME AND AWAY TEAM

In [17]:
# Ensure numeric
matches_cleaned['FTHome'] = pd.to_numeric(matches_cleaned['FTHome'], errors='coerce')
matches_cleaned['FTAway'] = pd.to_numeric(matches_cleaned['FTAway'], errors='coerce')

# --- Home team conceded at home: rolling avg conceded in last 20 HOME matches (exclude current) ---
matches_cleaned['HomeConcededHomeRolling20'] = (
    matches_cleaned
    .groupby('HomeTeam')['FTAway']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

# --- Away team conceded away: rolling avg conceded in last 20 AWAY matches (exclude current) ---
matches_cleaned['AwayConcededAwayRolling20'] = (
    matches_cleaned
    .groupby('AwayTeam')['FTHome']
    .apply(lambda s: s.shift(1).rolling(window=20, min_periods=1).mean())
    .reset_index(level=0, drop=True)
)

In [18]:
matches_features = matches_cleaned[['HomeElo', 'AwayElo', 
    'Form3Home', 'Form5Home', 'Form3Away', 'Form5Away', 
    'FTResult', 
    'HomeTotalPointsRoll20', 'AwayTotalPointsRoll20',
    'HomeTeamHomePointsRolling20', 'AwayTeamAwayPointsRolling20', 
    'HomeTeamShotsRolling20', 'AwayTeamShotsRolling20', 
    'HomeTeamShotsHomeRolling20', 'AwayTeamShotsAwayRolling20', 
    'HomeTeamTargetShotsRolling20', 'AwayTeamTargetShotsRolling20', 
    'HomeTotalGoalsRolling20', 'AwayTotalGoalsRolling20', 
    'HomeGoalsHomeRolling20', 'AwayGoalsAwayRolling20', 
    'HomeConcededHomeRolling20','AwayConcededAwayRolling20', 'HomeOdds', 'DrawOdds', 'AwayOdds']]

In [19]:
matches_features

,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,Form5Away,FTResult,HomeTotalPointsRoll20,AwayTotalPointsRoll20,HomeTeamHomePointsRolling20,AwayTeamAwayPointsRolling20,HomeTeamShotsRolling20,AwayTeamShotsRolling20,HomeTeamShotsHomeRolling20,AwayTeamShotsAwayRolling20,HomeTeamTargetShotsRolling20,AwayTeamTargetShotsRolling20,HomeTotalGoalsRolling20,AwayTotalGoalsRolling20,HomeGoalsHomeRolling20,AwayGoalsAwayRolling20,HomeConcededHomeRolling20,AwayConcededAwayRolling20,HomeOdds,DrawOdds,AwayOdds
0,1608.77,1579.99,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.436364,0.290909,0.272727
1,1800.17,1681.36,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.583075,0.252094,0.164831
2,1635.61,1679.18,0.0,0.0,0.0,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.410959,0.294521,0.294521
3,1636.08,1630.02,0.0,0.0,0.0,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.440497,0.284192,0.275311
4,1782.55,1685.55,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.530864,0.265432,0.203704
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9320,1799.76,1880.42,5.0,8.0,6.0,12.0,2,1.70,1.55,1.50,1.55,11.65,16.05,13.30,13.80,4.3,5.55,1.80,1.30,1.45,1.65,1.10,1.40,0.309101,0.256753,0.434146
9321,1557.66,1985.45,1.0,2.0,4.0,8.0,2,0.30,1.90,0.35,1.90,9.10,14.15,8.80,11.90,3.0,4.55,0.70,1.65,0.80,1.80,2.55,0.90,0.100538,0.162964,0.736498
9322,1882.33,1776.20,4.0,7.0,7.0,7.0,2,2.00,1.45,2.10,1.10,13.75,9.65,15.85,9.70,4.7,3.90,2.05,1.35,2.30,0.85,1.05,1.20,0.721382,0.170040,0.108578
9323,2008.67,1820.28,1.0,7.0,7.0,9.0,1,2.05,1.80,2.55,1.55,17.95,13.40,18.05,13.15,5.8,5.00,2.25,1.60,2.35,1.50,0.85,1.30,0.679776,0.168440,0.151784
9324,1739.45,1820.23,0.0,6.0,6.0,12.0,1,1.45,1.60,1.15,1.35,11.45,12.35,11.20,10.15,4.1,4.70,1.30,1.65,1.45,1.35,1.75,1.15,0.352613,0.254144,0.393243

DIFFERENCE FEATURES

In [20]:
matches_features['TotalPointsRoll20_diff'] = matches_features['AwayTotalPointsRoll20'] - matches_features['HomeTotalPointsRoll20']

matches_features['HomeAwayPointsRolling20_diff'] = matches_features['AwayTeamAwayPointsRolling20'] - matches_features['HomeTeamHomePointsRolling20']

matches_features['ShotsRolling20_diff'] = matches_features['AwayTeamShotsRolling20'] - matches_features['HomeTeamShotsRolling20']

matches_features['ShotsHomeAwayRolling20_diff'] = matches_features['AwayTeamShotsAwayRolling20'] - matches_features['HomeTeamShotsHomeRolling20']

matches_features['TargetShotsRolling20_diff'] = matches_features['AwayTeamTargetShotsRolling20'] - matches_features['HomeTeamTargetShotsRolling20']

matches_features['GoalsRolling20_diff'] = matches_features['AwayTotalGoalsRolling20'] - matches_features['HomeTotalGoalsRolling20']

matches_features['GoalsHomeAwayRolling20_diff'] = matches_features['AwayGoalsAwayRolling20'] - matches_features['HomeGoalsHomeRolling20']

matches_features['ConcededHomeAwayRolling20_diff'] = matches_features['AwayConcededAwayRolling20'] - matches_features['HomeConcededHomeRolling20']

C:\Users\mikko\AppData\Local\Temp\ipykernel_24156\991253460.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['TotalPointsRoll20_diff'] = matches_features['AwayTotalPointsRoll20'] - matches_features['HomeTotalPointsRoll20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_24156\991253460.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['HomeAwayPointsRolling20_diff'] = matches_features['AwayTeamAwayPointsRolling20'] - matches_features['HomeTeamHomePointsRolling20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_24156\991253460.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['ShotsRolling20_diff'] = matches_features['AwayTeamShotsRolling20'] - matches_features['HomeTeamShotsRolling20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_24156\991253460.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['ShotsHomeAwayRolling20_diff'] = matches_features['AwayTeamShotsAwayRolling20'] - matches_features['HomeTeamShotsHomeRolling20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_24156\991253460.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['TargetShotsRolling20_diff'] = matches_features['AwayTeamTargetShotsRolling20'] - matches_features['HomeTeamTargetShotsRolling20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_24156\991253460.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['GoalsRolling20_diff'] = matches_features['AwayTotalGoalsRolling20'] - matches_features['HomeTotalGoalsRolling20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_24156\991253460.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['GoalsHomeAwayRolling20_diff'] = matches_features['AwayGoalsAwayRolling20'] - matches_features['HomeGoalsHomeRolling20']
C:\Users\mikko\AppData\Local\Temp\ipykernel_24156\991253460.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features['ConcededHomeAwayRolling20_diff'] = matches_features['AwayConcededAwayRolling20'] - matches_features['HomeConcededHomeRolling20']

INTEGERS

In [21]:
int_cols = ['Form3Home', 'Form5Home', 'Form3Away', 'Form5Away', 'FTResult']

# convert specific columns to int
matches_features[int_cols] = matches_features[int_cols].astype('int64')

# convert the rest to float
matches_features.loc[:, ~matches_features.columns.isin(int_cols)] = matches_features.loc[:, ~matches_features.columns.isin(int_cols)].astype('float64')

C:\Users\mikko\AppData\Local\Temp\ipykernel_24156\442490929.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_features[int_cols] = matches_features[int_cols].astype('int64')

FEATURES AND TARGET (X, y)

In [22]:
matches_features = matches_features.dropna()

X = matches_features.drop(['FTResult', 'HomeOdds', 'DrawOdds', 'AwayOdds'], axis=1)
y = matches_features['FTResult']

In [23]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9253 entries, 19 to 9324
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   HomeElo                         9253 non-null   float64
 1   AwayElo                         9253 non-null   float64
 2   Form3Home                       9253 non-null   int64
 3   Form5Home                       9253 non-null   int64
 4   Form3Away                       9253 non-null   int64
 5   Form5Away                       9253 non-null   int64
 6   HomeTotalPointsRoll20           9253 non-null   float64
 7   AwayTotalPointsRoll20           9253 non-null   float64
 8   HomeTeamHomePointsRolling20     9253 non-null   float64
 9   AwayTeamAwayPointsRolling20     9253 non-null   float64
 10  HomeTeamShotsRolling20          9253 non-null   float64
 11  AwayTeamShotsRolling20          9253 non-null   float64
 12  HomeTeamShotsHomeRolling20      9253 non-null   float64
 13  AwayTeamShotsAwayRolling20      9253 non-null   float64
 14  HomeTeamTargetShotsRolling20    9253 non-null   float64
 15  AwayTeamTargetShotsRolling20    9253 non-null   float64
 16  HomeTotalGoalsRolling20         9253 non-null   float64
 17  AwayTotalGoalsRolling20         9253 non-null   float64
 18  HomeGoalsHomeRolling20          9253 non-null   float64
 19  AwayGoalsAwayRolling20          9253 non-null   float64
 20  HomeConcededHomeRolling20       9253 non-null   float64
 21  AwayConcededAwayRolling20       9253 non-null   float64
 22  TotalPointsRoll20_diff          9253 non-null   float64
 23  HomeAwayPointsRolling20_diff    9253 non-null   float64
 24  ShotsRolling20_diff             9253 non-null   float64
 25  ShotsHomeAwayRolling20_diff     9253 non-null   float64
 26  TargetShotsRolling20_diff       9253 non-null   float64
 27  GoalsRolling20_diff             9253 non-null   float64
 28  GoalsHomeAwayRolling20_diff     9253 non-null   float64
 29  ConcededHomeAwayRolling20_diff  9253 non-null   float64
dtypes: float64(26), int64(4)
memory usage: 2.2 MB

TRAIN AND TEST DATA SPLIT

In [24]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    shuffle=False
)

RANDOM FOREST TRAIN

In [25]:
rf = RandomForestClassifier(
    n_estimators=1500,
    max_depth=None,
    min_samples_split=10,
    min_samples_leaf=5,
    max_features="sqrt",
    class_weight="balanced_subsample", 
    n_jobs=-1,
    random_state=42
)

rf.fit(X_train, y_train)

# Predict class + probabilities
pred_rf = rf.predict(X_test)
proba_rf = rf.predict_proba(X_test)

print("Accuracy:", accuracy_score(y_test, pred_rf))
print("LogLoss:", log_loss(y_test, proba_rf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_rf))
print("\nClassification Report:\n", classification_report(y_test, pred_rf, digits=3))

Accuracy: 0.5180983252296056
LogLoss: 0.9922140553144067

Confusion Matrix:
 [[534  72 193]
 [193  45 189]
 [178  67 380]]

Classification Report:
               precision    recall  f1-score   support

           0      0.590     0.668     0.627       799
           1      0.245     0.105     0.147       427
           2      0.499     0.608     0.548       625

    accuracy                          0.518      1851
   macro avg      0.444     0.461     0.441      1851
weighted avg      0.480     0.518     0.490      1851

In [26]:
imp = pd.Series(rf.feature_importances_, index=X_train.columns).sort_values(ascending=False)
print(imp.head(25))

TargetShotsRolling20_diff         0.051744
ShotsRolling20_diff               0.051386
AwayElo                           0.051300
HomeElo                           0.048247
ShotsHomeAwayRolling20_diff       0.046555
HomeAwayPointsRolling20_diff      0.044198
TotalPointsRoll20_diff            0.041264
GoalsHomeAwayRolling20_diff       0.038076
AwayTeamShotsRolling20            0.036753
GoalsRolling20_diff               0.036711
AwayTeamShotsAwayRolling20        0.036642
HomeTeamShotsHomeRolling20        0.036101
HomeTeamShotsRolling20            0.034982
ConcededHomeAwayRolling20_diff    0.034312
HomeTeamTargetShotsRolling20      0.034026
AwayTeamTargetShotsRolling20      0.032355
HomeGoalsHomeRolling20            0.029267
HomeConcededHomeRolling20         0.028351
AwayTotalPointsRoll20             0.027963
AwayTeamAwayPointsRolling20       0.027650
HomeTeamHomePointsRolling20       0.027443
AwayConcededAwayRolling20         0.027288
HomeTotalPointsRoll20             0.026820
AwayTotalGoalsRolling20           0.026456
HomeTotalGoalsRolling20           0.025889
dtype: float64

In [27]:
X_rf_last = X_test.iloc[[-1]]   # double brackets keep it 2D

pred_rf_last = rf.predict(X_rf_last)
proba_rf_last = rf.predict_proba(X_rf_last)

print("Predicted class:", pred_rf_last)
print("Probabilities:", proba_rf_last)

Predicted class: [2]
Probabilities: [[0.25341822 0.26727161 0.47931017]]

In [ ]:
pred_y_rf = rf.predict(X_test)
proba_rf = rf.predict_proba(X_test)
proba_rf_df = pd.DataFrame(proba_rf, columns=['pred_rf_H', 'pred_rf_D', 'pred_rf_A'])
proba_rf_df

      pred_rf_H  pred_rf_D  pred_rf_A
0      0.167714   0.231159   0.601127
1      0.392062   0.345427   0.262512
2      0.261085   0.390630   0.348285
3      0.469652   0.308349   0.221999
4      0.476618   0.316039   0.207343
...         ...        ...        ...
1846   0.184994   0.312077   0.502929
1847   0.124843   0.147624   0.727533
1848   0.642881   0.228213   0.128906
1849   0.648316   0.202799   0.148885
1850   0.253418   0.267272   0.479310

[1851 rows x 3 columns]

In [29]:
Features_last1851 = matches_features.iloc[-len(proba_rf_df):][['HomeOdds','DrawOdds','AwayOdds']].reset_index(drop=True)

proba_rf_df = pd.concat([proba_rf_df.reset_index(drop=True), Features_last1851], axis=1)

In [30]:
proba_rf_df['total_prob'] = proba_rf_df['HomeOdds'] + proba_rf_df['DrawOdds'] + proba_rf_df['AwayOdds']
proba_rf_df

,pred_rf_H,pred_rf_D,pred_rf_A,HomeOdds,DrawOdds,AwayOdds,total_prob
0,0.167714,0.231159,0.601127,0.200669,0.235097,0.564234,1.0
1,0.392062,0.345427,0.262512,0.454605,0.288920,0.256475,1.0
2,0.261085,0.390630,0.348285,0.357701,0.294966,0.347333,1.0
3,0.469652,0.308349,0.221999,0.591714,0.228777,0.179509,1.0
4,0.476618,0.316039,0.207343,0.507399,0.251043,0.241558,1.0
...,...,...,...,...,...,...,...
1846,0.184994,0.312077,0.502929,0.309101,0.256753,0.434146,1.0
1847,0.124843,0.147624,0.727533,0.100538,0.162964,0.736498,1.0
1848,0.642881,0.228213,0.128906,0.721382,0.170040,0.108578,1.0
1849,0.648316,0.202799,0.148885,0.679776,0.168440,0.151784,1.0
1850,0.253418,0.267272,0.479310,0.352613,0.254144,0.393243,1.0

In [31]:
proba_rf_rng = rf.predict_proba(X_test)

rng = np.random.default_rng(42)

pred_rf_rng = np.array([
    rng.choice(len(p), p=p) for p in proba_rf_rng
])

In [32]:
print("Accuracy:", accuracy_score(y_test, pred_rf_rng))
print("LogLoss:", log_loss(y_test, proba_rf_rng))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_rf_rng))
print("\nClassification Report:\n", classification_report(y_test, pred_rf_rng, digits=3))

Accuracy: 0.4100486223662885
LogLoss: 0.9922140553144067

Confusion Matrix:
 [[360 218 221]
 [156 130 141]
 [199 157 269]]

Classification Report:
               precision    recall  f1-score   support

           0      0.503     0.451     0.476       799
           1      0.257     0.304     0.279       427
           2      0.426     0.430     0.428       625

    accuracy                          0.410      1851
   macro avg      0.396     0.395     0.394      1851
weighted avg      0.421     0.410     0.414      1851

In [33]:

SEED = 42

def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 400, 2500),
        "max_depth": trial.suggest_int("max_depth", 4, 60),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 40),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 25),
        "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2", None]),
        "bootstrap": trial.suggest_categorical("bootstrap", [True, False]),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced", "balanced_subsample"]),
        "n_jobs": -1,
        "random_state": SEED,
    }

    model_rf = RandomForestClassifier(**params)

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

    # Optimize for probability quality (lower log loss is better)
    scores = cross_val_score(
        model_rf,
        X_train,
        y_train,
        cv=cv,
        scoring="neg_log_loss",
        n_jobs=-1
    )

    return float(np.mean(scores))  # maximize neg_log_loss

# Study
study = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=SEED)
)

study.optimize(objective, n_trials=60, show_progress_bar=True)

print("\nBest CV neg_log_loss:", study.best_value)
print("Best params:\n", study.best_params)

# Train final model with best params
rf_opt = RandomForestClassifier(
    **study.best_params,
    n_jobs=-1,
    random_state=SEED
)
rf_opt.fit(X_train, y_train)

[I 2026-03-10 20:28:32,576] A new study created in memory with name: no-name-951071b4-b6a8-4e97-a699-10cd5bc40f21
Best trial: 0. Best value: -0.999542:   2%|▏         | 1/60 [00:09<09:43,  9.89s/it]

[I 2026-03-10 20:28:42,469] Trial 0 finished with value: -0.999542371958716 and parameters: {'n_estimators': 1186, 'max_depth': 58, 'min_samples_split': 30, 'min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': 'balanced_subsample'}. Best is trial 0 with value: -0.999542371958716.

Best trial: 1. Best value: -0.997586:   3%|▎         | 2/60 [00:29<15:14, 15.76s/it]

[I 2026-03-10 20:29:02,346] Trial 1 finished with value: -0.9975862205624599 and parameters: {'n_estimators': 2148, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 'log2', 'bootstrap': False, 'class_weight': 'balanced_subsample'}. Best is trial 1 with value: -0.9975862205624599.

Best trial: 1. Best value: -0.997586:   5%|▌         | 3/60 [01:03<22:55, 24.12s/it]

[I 2026-03-10 20:29:36,419] Trial 2 finished with value: -0.9985735008879381 and parameters: {'n_estimators': 1358, 'max_depth': 48, 'min_samples_split': 9, 'min_samples_leaf': 13, 'max_features': None, 'bootstrap': True, 'class_weight': 'balanced'}. Best is trial 1 with value: -0.9975862205624599.

Best trial: 3. Best value: -0.97549:   7%|▋         | 4/60 [01:09<15:51, 17.00s/it]

[I 2026-03-10 20:29:42,495] Trial 3 finished with value: -0.9754903372609924 and parameters: {'n_estimators': 1039, 'max_depth': 9, 'min_samples_split': 28, 'min_samples_leaf': 12, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 3 with value: -0.9754903372609924.

Best trial: 3. Best value: -0.97549:   8%|▊         | 5/60 [01:19<13:06, 14.30s/it]

[I 2026-03-10 20:29:52,016] Trial 4 finished with value: -1.0013098073293683 and parameters: {'n_estimators': 1548, 'max_depth': 14, 'min_samples_split': 39, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: -0.9754903372609924.

Best trial: 3. Best value: -0.97549:  10%|█         | 6/60 [01:25<10:19, 11.48s/it]

[I 2026-03-10 20:29:58,016] Trial 5 finished with value: -0.9770664438445245 and parameters: {'n_estimators': 1216, 'max_depth': 19, 'min_samples_split': 34, 'min_samples_leaf': 9, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 3 with value: -0.9754903372609924.

Best trial: 3. Best value: -0.97549:  12%|█▏        | 7/60 [01:28<07:41,  8.71s/it]

[I 2026-03-10 20:30:01,033] Trial 6 finished with value: -0.9783245587064033 and parameters: {'n_estimators': 411, 'max_depth': 50, 'min_samples_split': 29, 'min_samples_leaf': 19, 'max_features': 'sqrt', 'bootstrap': False, 'class_weight': None}. Best is trial 3 with value: -0.9754903372609924.

Best trial: 3. Best value: -0.97549:  13%|█▎        | 8/60 [01:36<07:27,  8.60s/it]

[I 2026-03-10 20:30:09,387] Trial 7 finished with value: -1.0033595482362583 and parameters: {'n_estimators': 1053, 'max_depth': 22, 'min_samples_split': 30, 'min_samples_leaf': 16, 'max_features': 'sqrt', 'bootstrap': False, 'class_weight': 'balanced'}. Best is trial 3 with value: -0.9754903372609924.

Best trial: 3. Best value: -0.97549:  15%|█▌        | 9/60 [01:51<08:56, 10.53s/it]

[I 2026-03-10 20:30:24,148] Trial 8 finished with value: -0.9933983290437102 and parameters: {'n_estimators': 1498, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2', 'bootstrap': False, 'class_weight': 'balanced_subsample'}. Best is trial 3 with value: -0.9754903372609924.

Best trial: 3. Best value: -0.97549:  17%|█▋        | 10/60 [01:55<07:09,  8.60s/it]

[I 2026-03-10 20:30:28,437] Trial 9 finished with value: -1.0009009614074753 and parameters: {'n_estimators': 880, 'max_depth': 8, 'min_samples_split': 13, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': 'balanced'}. Best is trial 3 with value: -0.9754903372609924.

Best trial: 10. Best value: -0.974564:  18%|█▊        | 11/60 [02:17<10:16, 12.58s/it]

[I 2026-03-10 20:30:50,050] Trial 10 finished with value: -0.9745640610407668 and parameters: {'n_estimators': 2032, 'max_depth': 4, 'min_samples_split': 21, 'min_samples_leaf': 24, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  20%|██        | 12/60 [02:48<14:33, 18.19s/it]

[I 2026-03-10 20:31:21,066] Trial 11 finished with value: -0.9746348902197532 and parameters: {'n_estimators': 2413, 'max_depth': 5, 'min_samples_split': 22, 'min_samples_leaf': 25, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  22%|██▏       | 13/60 [03:20<17:31, 22.37s/it]

[I 2026-03-10 20:31:53,069] Trial 12 finished with value: -0.9746292462977122 and parameters: {'n_estimators': 2485, 'max_depth': 5, 'min_samples_split': 20, 'min_samples_leaf': 25, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  23%|██▎       | 14/60 [04:00<21:20, 27.84s/it]

[I 2026-03-10 20:32:33,549] Trial 13 finished with value: -0.9777827697668432 and parameters: {'n_estimators': 1925, 'max_depth': 38, 'min_samples_split': 20, 'min_samples_leaf': 25, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  25%|██▌       | 15/60 [04:28<20:42, 27.61s/it]

[I 2026-03-10 20:33:00,602] Trial 14 finished with value: -0.9745682354901326 and parameters: {'n_estimators': 2481, 'max_depth': 4, 'min_samples_split': 19, 'min_samples_leaf': 21, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  27%|██▋       | 16/60 [05:10<23:26, 31.96s/it]

[I 2026-03-10 20:33:42,683] Trial 15 finished with value: -0.978267229665682 and parameters: {'n_estimators': 1890, 'max_depth': 32, 'min_samples_split': 15, 'min_samples_leaf': 21, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  28%|██▊       | 17/60 [05:57<26:16, 36.67s/it]

[I 2026-03-10 20:34:30,309] Trial 16 finished with value: -0.9781252321978245 and parameters: {'n_estimators': 2175, 'max_depth': 25, 'min_samples_split': 16, 'min_samples_leaf': 22, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  30%|███       | 18/60 [06:39<26:49, 38.31s/it]

[I 2026-03-10 20:35:12,436] Trial 17 finished with value: -0.9785951780786517 and parameters: {'n_estimators': 1795, 'max_depth': 13, 'min_samples_split': 25, 'min_samples_leaf': 17, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  32%|███▏      | 19/60 [08:03<35:35, 52.08s/it]

[I 2026-03-10 20:36:36,578] Trial 18 finished with value: -1.8866263873108466 and parameters: {'n_estimators': 2208, 'max_depth': 39, 'min_samples_split': 24, 'min_samples_leaf': 22, 'max_features': None, 'bootstrap': False, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  33%|███▎      | 20/60 [08:24<28:21, 42.54s/it]

[I 2026-03-10 20:36:56,908] Trial 19 finished with value: -1.0073596781615826 and parameters: {'n_estimators': 1752, 'max_depth': 4, 'min_samples_split': 18, 'min_samples_leaf': 18, 'max_features': None, 'bootstrap': True, 'class_weight': 'balanced'}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  35%|███▌      | 21/60 [09:26<31:32, 48.53s/it]

[I 2026-03-10 20:37:59,383] Trial 20 finished with value: -0.9799189381569506 and parameters: {'n_estimators': 2301, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  37%|███▋      | 22/60 [09:55<26:59, 42.61s/it]

[I 2026-03-10 20:38:28,194] Trial 21 finished with value: -0.9745659622363103 and parameters: {'n_estimators': 2483, 'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 24, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  38%|███▊      | 23/60 [10:38<26:19, 42.68s/it]

[I 2026-03-10 20:39:11,032] Trial 22 finished with value: -0.9769827677375179 and parameters: {'n_estimators': 2034, 'max_depth': 9, 'min_samples_split': 23, 'min_samples_leaf': 23, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  40%|████      | 24/60 [11:35<28:15, 47.09s/it]

[I 2026-03-10 20:40:08,414] Trial 23 finished with value: -0.9780673655790132 and parameters: {'n_estimators': 2484, 'max_depth': 19, 'min_samples_split': 18, 'min_samples_leaf': 23, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  42%|████▏     | 25/60 [12:03<23:59, 41.14s/it]

[I 2026-03-10 20:40:35,661] Trial 24 finished with value: -0.9745924104319265 and parameters: {'n_estimators': 2345, 'max_depth': 4, 'min_samples_split': 13, 'min_samples_leaf': 20, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  43%|████▎     | 26/60 [12:48<23:58, 42.31s/it]

[I 2026-03-10 20:41:20,692] Trial 25 finished with value: -0.9772324486974668 and parameters: {'n_estimators': 2088, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 25, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  45%|████▌     | 27/60 [13:51<26:48, 48.73s/it]

[I 2026-03-10 20:42:24,415] Trial 26 finished with value: -1.8676274365745242 and parameters: {'n_estimators': 1687, 'max_depth': 18, 'min_samples_split': 27, 'min_samples_leaf': 23, 'max_features': None, 'bootstrap': False, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  47%|████▋     | 28/60 [14:47<27:09, 50.93s/it]

[I 2026-03-10 20:43:20,461] Trial 27 finished with value: -0.9785457351599576 and parameters: {'n_estimators': 2293, 'max_depth': 14, 'min_samples_split': 34, 'min_samples_leaf': 19, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  48%|████▊     | 29/60 [14:56<19:41, 38.12s/it]

[I 2026-03-10 20:43:28,690] Trial 28 finished with value: -1.003441218863755 and parameters: {'n_estimators': 1967, 'max_depth': 8, 'min_samples_split': 17, 'min_samples_leaf': 23, 'max_features': 'log2', 'bootstrap': True, 'class_weight': 'balanced'}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  50%|█████     | 30/60 [16:03<23:30, 47.02s/it]

[I 2026-03-10 20:44:36,499] Trial 29 finished with value: -0.9995530782513319 and parameters: {'n_estimators': 2494, 'max_depth': 56, 'min_samples_split': 20, 'min_samples_leaf': 15, 'max_features': None, 'bootstrap': True, 'class_weight': 'balanced_subsample'}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  52%|█████▏    | 31/60 [16:19<18:10, 37.60s/it]

[I 2026-03-10 20:44:52,113] Trial 30 finished with value: -1.0015130513693073 and parameters: {'n_estimators': 2240, 'max_depth': 22, 'min_samples_split': 25, 'min_samples_leaf': 21, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': 'balanced_subsample'}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  53%|█████▎    | 32/60 [16:54<17:07, 36.71s/it]

[I 2026-03-10 20:45:26,749] Trial 31 finished with value: -0.9746043491673495 and parameters: {'n_estimators': 2342, 'max_depth': 5, 'min_samples_split': 13, 'min_samples_leaf': 19, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  55%|█████▌    | 33/60 [17:22<15:19, 34.05s/it]

[I 2026-03-10 20:45:54,588] Trial 32 finished with value: -0.9745847061150898 and parameters: {'n_estimators': 2344, 'max_depth': 4, 'min_samples_split': 12, 'min_samples_leaf': 21, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  57%|█████▋    | 34/60 [18:12<16:57, 39.12s/it]

[I 2026-03-10 20:46:45,537] Trial 33 finished with value: -0.9781664802673632 and parameters: {'n_estimators': 2122, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 17, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 10. Best value: -0.974564:  58%|█████▊    | 35/60 [19:17<19:25, 46.62s/it]

[I 2026-03-10 20:47:49,652] Trial 34 finished with value: -0.9794553371617614 and parameters: {'n_estimators': 2387, 'max_depth': 16, 'min_samples_split': 11, 'min_samples_leaf': 14, 'max_features': None, 'bootstrap': True, 'class_weight': None}. Best is trial 10 with value: -0.9745640610407668.

Best trial: 35. Best value: -0.974291:  60%|██████    | 36/60 [19:25<14:01, 35.07s/it]

[I 2026-03-10 20:47:57,780] Trial 35 finished with value: -0.9742914989887822 and parameters: {'n_estimators': 2049, 'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 24, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  62%|██████▏   | 37/60 [19:36<10:44, 28.03s/it]

[I 2026-03-10 20:48:09,373] Trial 36 finished with value: -1.0055169604059664 and parameters: {'n_estimators': 2051, 'max_depth': 8, 'min_samples_split': 16, 'min_samples_leaf': 24, 'max_features': 'log2', 'bootstrap': False, 'class_weight': 'balanced_subsample'}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  63%|██████▎   | 38/60 [19:45<08:09, 22.26s/it]

[I 2026-03-10 20:48:18,179] Trial 37 finished with value: -0.9748569009194809 and parameters: {'n_estimators': 1844, 'max_depth': 16, 'min_samples_split': 21, 'min_samples_leaf': 24, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  65%|██████▌   | 39/60 [19:53<06:15, 17.90s/it]

[I 2026-03-10 20:48:25,908] Trial 38 finished with value: -1.0026005789403327 and parameters: {'n_estimators': 1615, 'max_depth': 8, 'min_samples_split': 31, 'min_samples_leaf': 11, 'max_features': 'log2', 'bootstrap': True, 'class_weight': 'balanced'}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  67%|██████▋   | 40/60 [20:02<05:07, 15.39s/it]

[I 2026-03-10 20:48:35,439] Trial 39 finished with value: -0.9767729694494719 and parameters: {'n_estimators': 1405, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 22, 'max_features': 'log2', 'bootstrap': False, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  68%|██████▊   | 41/60 [20:06<03:46, 11.93s/it]

[I 2026-03-10 20:48:39,283] Trial 40 finished with value: -1.0030907875451576 and parameters: {'n_estimators': 610, 'max_depth': 7, 'min_samples_split': 19, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True, 'class_weight': 'balanced_subsample'}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  70%|███████   | 42/60 [20:15<03:15, 10.88s/it]

[I 2026-03-10 20:48:47,724] Trial 41 finished with value: -0.9752204862705135 and parameters: {'n_estimators': 2224, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  72%|███████▏  | 43/60 [20:25<03:01, 10.65s/it]

[I 2026-03-10 20:48:57,827] Trial 42 finished with value: -0.9743215811382907 and parameters: {'n_estimators': 2406, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 21, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  73%|███████▎  | 44/60 [20:36<02:52, 10.79s/it]

[I 2026-03-10 20:49:08,940] Trial 43 finished with value: -0.9748539086651613 and parameters: {'n_estimators': 2433, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 24, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  75%|███████▌  | 45/60 [20:41<02:16,  9.13s/it]

[I 2026-03-10 20:49:14,205] Trial 44 finished with value: -0.9744613247985651 and parameters: {'n_estimators': 1296, 'max_depth': 7, 'min_samples_split': 22, 'min_samples_leaf': 21, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  77%|███████▋  | 46/60 [20:47<01:55,  8.23s/it]

[I 2026-03-10 20:49:20,342] Trial 45 finished with value: -0.9749396310045075 and parameters: {'n_estimators': 1194, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 24, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  78%|███████▊  | 47/60 [20:53<01:36,  7.39s/it]

[I 2026-03-10 20:49:25,754] Trial 46 finished with value: -0.974573394835244 and parameters: {'n_estimators': 1260, 'max_depth': 7, 'min_samples_split': 22, 'min_samples_leaf': 8, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  80%|████████  | 48/60 [21:00<01:27,  7.27s/it]

[I 2026-03-10 20:49:32,759] Trial 47 finished with value: -1.004405225026821 and parameters: {'n_estimators': 1021, 'max_depth': 35, 'min_samples_split': 27, 'min_samples_leaf': 22, 'max_features': 'log2', 'bootstrap': False, 'class_weight': 'balanced'}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  82%|████████▏ | 49/60 [21:07<01:18,  7.16s/it]

[I 2026-03-10 20:49:39,671] Trial 48 finished with value: -0.9749640789742454 and parameters: {'n_estimators': 1519, 'max_depth': 23, 'min_samples_split': 5, 'min_samples_leaf': 25, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  83%|████████▎ | 50/60 [21:15<01:14,  7.48s/it]

[I 2026-03-10 20:49:47,905] Trial 49 finished with value: -0.9750138929630247 and parameters: {'n_estimators': 1983, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 35. Best value: -0.974291:  85%|████████▌ | 51/60 [21:22<01:05,  7.25s/it]

[I 2026-03-10 20:49:54,604] Trial 50 finished with value: -0.9758738589425974 and parameters: {'n_estimators': 1334, 'max_depth': 17, 'min_samples_split': 25, 'min_samples_leaf': 18, 'max_features': 'log2', 'bootstrap': True, 'class_weight': None}. Best is trial 35 with value: -0.9742914989887822.

Best trial: 51. Best value: -0.974278:  87%|████████▋ | 52/60 [21:31<01:02,  7.78s/it]

[I 2026-03-10 20:50:03,629] Trial 51 finished with value: -0.974277886862988 and parameters: {'n_estimators': 2191, 'max_depth': 6, 'min_samples_split': 22, 'min_samples_leaf': 21, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 51 with value: -0.974277886862988.

Best trial: 51. Best value: -0.974278:  88%|████████▊ | 53/60 [21:43<01:03,  9.09s/it]

[I 2026-03-10 20:50:15,766] Trial 52 finished with value: -0.9757075906657464 and parameters: {'n_estimators': 2130, 'max_depth': 44, 'min_samples_split': 21, 'min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 51 with value: -0.974277886862988.

Best trial: 51. Best value: -0.974278:  90%|█████████ | 54/60 [21:48<00:48,  8.09s/it]

[I 2026-03-10 20:50:21,524] Trial 53 finished with value: -0.9754906310441631 and parameters: {'n_estimators': 1093, 'max_depth': 10, 'min_samples_split': 23, 'min_samples_leaf': 22, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 51 with value: -0.974277886862988.

Best trial: 54. Best value: -0.974275:  92%|█████████▏| 55/60 [21:58<00:42,  8.47s/it]

[I 2026-03-10 20:50:30,875] Trial 54 finished with value: -0.9742748203256276 and parameters: {'n_estimators': 2277, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 21, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 54 with value: -0.9742748203256276.

Best trial: 54. Best value: -0.974275:  93%|█████████▎| 56/60 [22:07<00:34,  8.68s/it]

[I 2026-03-10 20:50:40,051] Trial 55 finished with value: -0.9743534468074759 and parameters: {'n_estimators': 2208, 'max_depth': 6, 'min_samples_split': 15, 'min_samples_leaf': 18, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 54 with value: -0.9742748203256276.

Best trial: 54. Best value: -0.974275:  95%|█████████▌| 57/60 [22:20<00:30, 10.13s/it]

[I 2026-03-10 20:50:53,576] Trial 56 finished with value: -0.976120314894328 and parameters: {'n_estimators': 2262, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 17, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 54 with value: -0.9742748203256276.

Best trial: 54. Best value: -0.974275:  97%|█████████▋| 58/60 [22:33<00:21, 10.91s/it]

[I 2026-03-10 20:51:06,293] Trial 57 finished with value: -0.9760547579654901 and parameters: {'n_estimators': 2161, 'max_depth': 28, 'min_samples_split': 17, 'min_samples_leaf': 18, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 54 with value: -0.9742748203256276.

Best trial: 54. Best value: -0.974275:  98%|█████████▊| 59/60 [22:44<00:10, 10.78s/it]

[I 2026-03-10 20:51:16,783] Trial 58 finished with value: -1.006837881185493 and parameters: {'n_estimators': 1945, 'max_depth': 6, 'min_samples_split': 14, 'min_samples_leaf': 16, 'max_features': 'sqrt', 'bootstrap': False, 'class_weight': 'balanced'}. Best is trial 54 with value: -0.9742748203256276.

Best trial: 54. Best value: -0.974275: 100%|██████████| 60/60 [22:49<00:00, 22.82s/it]

[I 2026-03-10 20:51:22,019] Trial 59 finished with value: -0.975799214452505 and parameters: {'n_estimators': 955, 'max_depth': 10, 'min_samples_split': 18, 'min_samples_leaf': 19, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}. Best is trial 54 with value: -0.9742748203256276.

Best CV neg_log_loss: -0.9742748203256276
Best params:
 {'n_estimators': 2277, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 21, 'max_features': 'sqrt', 'bootstrap': True, 'class_weight': None}

RandomForestClassifier(max_depth=6, min_samples_leaf=21, min_samples_split=17,
                       n_estimators=2277, n_jobs=-1, random_state=42)

In [34]:
# Evaluate on test set
pred_rf_opt = rf_opt.predict(X_test)
proba_rf_opt = rf_opt.predict_proba(X_test)

proba_rf_opt_df = pd.DataFrame(proba_rf_opt, columns=['pred_rf_opt_H', 'pred_rf_opt_D', 'pred_rf_opt_A'])

In [36]:
Features_last1851 = matches_features.iloc[-len(proba_rf_df):][['HomeOdds','DrawOdds','AwayOdds']].reset_index(drop=True)

proba_rf_opt_df = pd.concat([proba_rf_opt_df.reset_index(drop=True), Features_last1851], axis=1)

In [37]:
proba_rf_opt_df

,pred_rf_opt_H,pred_rf_opt_D,pred_rf_opt_A,HomeOdds,DrawOdds,AwayOdds
0,0.232151,0.237537,0.530312,0.200669,0.235097,0.564234
1,0.477574,0.283111,0.239315,0.454605,0.288920,0.256475
2,0.378812,0.300436,0.320751,0.357701,0.294966,0.347333
3,0.534428,0.265993,0.199579,0.591714,0.228777,0.179509
4,0.569641,0.258686,0.171673,0.507399,0.251043,0.241558
...,...,...,...,...,...,...
1846,0.270574,0.270043,0.459383,0.309101,0.256753,0.434146
1847,0.143190,0.134263,0.722547,0.100538,0.162964,0.736498
1848,0.710732,0.184115,0.105153,0.721382,0.170040,0.108578
1849,0.674934,0.195237,0.129829,0.679776,0.168440,0.151784
1850,0.312698,0.270151,0.417151,0.352613,0.254144,0.393243

In [38]:
print("\nTEST Accuracy:", accuracy_score(y_test, pred_rf_opt))
print("TEST LogLoss:", log_loss(y_test, proba_rf_opt))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_rf_opt))
print("\nClassification Report:\n", classification_report(y_test, pred_rf_opt, digits=3))

TEST Accuracy: 0.5353862776877364
TEST LogLoss: 0.9783339444257058

Confusion Matrix:
 [[666   0 133]
 [279   0 148]
 [300   0 325]]

Classification Report:
               precision    recall  f1-score   support

           0      0.535     0.834     0.652       799
           1      0.000     0.000     0.000       427
           2      0.536     0.520     0.528       625

    accuracy                          0.535      1851
   macro avg      0.357     0.451     0.393      1851
weighted avg      0.412     0.535     0.460      1851

c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [42]:
proba_opt_rng = rf_opt.predict_proba(X_test)

rng = np.random.default_rng(42)

pred_opt_rng = np.array([
    rng.choice(len(p), p=p) for p in proba_opt_rng
])

In [43]:
print("TEST Accuracy:", accuracy_score(y_test, pred_opt_rng))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_rf_opt))
print("\nClassification Report:\n", classification_report(y_test, pred_opt_rng, digits=3))

TEST Accuracy: 0.43381955699621827

Confusion Matrix:
 [[666   0 133]
 [279   0 148]
 [300   0 325]]

Classification Report:
               precision    recall  f1-score   support

           0      0.513     0.533     0.523       799
           1      0.273     0.279     0.276       427
           2      0.441     0.413     0.426       625

    accuracy                          0.434      1851
   macro avg      0.409     0.408     0.408      1851
weighted avg      0.433     0.434     0.433      1851

In [44]:
X_rf_last = X_test.iloc[[-1]]   # double brackets keep it 2D

pred_rf_opt_last = rf_opt.predict(X_rf_last)
proba_rf_opt_last = rf_opt.predict_proba(X_rf_last)

print("Predicted class:", pred_rf_opt_last)
print("Probabilities:", proba_rf_opt_last)

Predicted class: [2]
Probabilities: [[0.31269795 0.27015091 0.41715114]]

In [33]:
model_xb = xgb.XGBClassifier(
    objective="multi:softprob",
    num_class=3,
    n_estimators=5000,
    learning_rate=0.1,      
    max_depth=4,            
    min_child_weight=5,
    subsample=0.9,
    colsample_bytree=0.9,
    reg_lambda=1.0,
    tree_method="hist",
    eval_metric="mlogloss",
    early_stopping_rounds=200,  
    random_state=42,
)

model_xb.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=100)

#metrics
proba_xb = model_xb.predict_proba(X_test)
pred_xb = proba_xb.argmax(axis=1)

print("Accuracy:", accuracy_score(y_test, pred_xb))
print("LogLoss:", log_loss(y_test, proba_xb))

print(confusion_matrix(y_test, pred_xb))
print(classification_report(y_test, pred_xb, digits=3))

[0]	validation_0-mlogloss:1.06005
[100]	validation_0-mlogloss:0.99728
[200]	validation_0-mlogloss:1.01779
[230]	validation_0-mlogloss:1.02362
Accuracy: 0.528372591006424
LogLoss: 0.9857930185095406
[[677   3 129]
 [281   1 148]
 [314   6 309]]
              precision    recall  f1-score   support

           0      0.532     0.837     0.651       809
           1      0.100     0.002     0.005       430
           2      0.527     0.491     0.509       629

    accuracy                          0.528      1868
   macro avg      0.387     0.443     0.388      1868
weighted avg      0.431     0.528     0.454      1868

In [34]:
X_xb_w_last = X_test.iloc[[-1]]   # double brackets keep it 2D

pred_xb_last = model_xb.predict(X_xb_w_last)
proba_xb_last = model_xb.predict_proba(X_xb_w_last)

print("Predicted class:", pred_xb_last)
print("Probabilities:", proba_xb_last)

Predicted class: [2]
Probabilities: [[0.3042779  0.23125075 0.4644713 ]]

In [35]:


SEED = 42
N_CLASSES = 3

# convert y if DataFrame with one column
if hasattr(y_train, "shape") and len(y_train.shape) == 2:
    y_train = y_train.iloc[:,0]
    y_test = y_test.iloc[:,0]

def objective(trial):

    params_xgbo = {
        "objective": "multi:softprob",
        "num_class": N_CLASSES,
        "tree_method": "hist",
        "eval_metric": "mlogloss",
        "random_state": SEED,
        "n_jobs": -1,

        # hyperparameters to tune
        "n_estimators": trial.suggest_int("n_estimators", 1000, 12000),
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 2, 10),
        "min_child_weight": trial.suggest_float("min_child_weight", 1.0, 20.0),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 50.0, log=True),

        "gamma": trial.suggest_float("gamma", 0.0, 10.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 5.0, log=True),

        # early stopping goes HERE for xgboost >=3
        "early_stopping_rounds": 200,
    }

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
    losses = []

    for tr_idx, va_idx in cv.split(X_train, y_train):

        X_tr = X_train.iloc[tr_idx]
        X_va = X_train.iloc[va_idx]
        y_tr = y_train.iloc[tr_idx]
        y_va = y_train.iloc[va_idx]

        model_xgb_o = xgb.XGBClassifier(**params_xgbo)

        model_xgb_o.fit(
            X_tr,
            y_tr,
            eval_set=[(X_va, y_va)],
            verbose=False
        )

        proba_xgbo = model_xgb_o.predict_proba(X_va)
        losses.append(log_loss(y_va, proba_xgbo, labels=np.arange(N_CLASSES)))

    return -np.mean(losses)


study_xgb = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(seed=SEED)
)

study_xgb.optimize(objective, n_trials=60, show_progress_bar=True)

print("\nBest CV neg_log_loss:", study_xgb.best_value)
print("Best params:\n", study_xgb.best_params)


# ---- train final optimized model ----

best_params_xgb = {
    **study_xgb.best_params,
    "objective": "multi:softprob",
    "num_class": N_CLASSES,
    "tree_method": "hist",
    "eval_metric": "mlogloss",
    "random_state": SEED,
    "n_jobs": -1,
    "early_stopping_rounds": 200,
}

model_xb_opt = xgb.XGBClassifier(**best_params_xgb)

model_xb_opt.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=100
)

[I 2026-03-09 21:14:47,834] A new study created in memory with name: no-name-b61601ba-99aa-4ea0-8a73-132127080ac1
Best trial: 0. Best value: -0.976339:   2%|▏         | 1/60 [00:04<04:54,  4.99s/it]

[I 2026-03-09 21:14:52,819] Trial 0 finished with value: -0.9763387531703787 and parameters: {'n_estimators': 5120, 'learning_rate': 0.2536999076681772, 'max_depth': 8, 'min_child_weight': 12.374511199743695, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.5779972601681014, 'reg_lambda': 0.0018747059221802516, 'gamma': 8.661761457749352, 'reg_alpha': 0.0016946556203947059}. Best is trial 0 with value: -0.9763387531703787.

Best trial: 1. Best value: -0.97428:   3%|▎         | 2/60 [00:13<06:52,  7.12s/it]

[I 2026-03-09 21:15:01,428] Trial 1 finished with value: -0.9742797887563178 and parameters: {'n_estimators': 8789, 'learning_rate': 0.010725209743171996, 'max_depth': 10, 'min_child_weight': 16.816410175208013, 'subsample': 0.6061695553391381, 'colsample_bytree': 0.5909124836035503, 'reg_lambda': 0.0072746531356694235, 'gamma': 3.0424224295953772, 'reg_alpha': 0.0003671474011048667}. Best is trial 1 with value: -0.9742797887563178.

Best trial: 1. Best value: -0.97428:   5%|▌         | 3/60 [00:24<08:24,  8.85s/it]

[I 2026-03-09 21:15:12,341] Trial 2 finished with value: -0.9750064197121926 and parameters: {'n_estimators': 5751, 'learning_rate': 0.02692655251486473, 'max_depth': 7, 'min_child_weight': 3.6503833523887947, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.6831809216468459, 'reg_lambda': 0.1390142035054592, 'gamma': 7.851759613930136, 'reg_alpha': 5.457028747569545e-07}. Best is trial 1 with value: -0.9742797887563178.

Best trial: 1. Best value: -0.97428:   7%|▋         | 4/60 [00:32<07:59,  8.57s/it]

[I 2026-03-09 21:15:20,484] Trial 3 finished with value: -0.9772731848715079 and parameters: {'n_estimators': 6657, 'learning_rate': 0.07500118950416987, 'max_depth': 2, 'min_child_weight': 12.54335218612733, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_lambda': 28.759721562259614, 'gamma': 9.656320330745594, 'reg_alpha': 0.10770212765048791}. Best is trial 1 with value: -0.9742797887563178.

Best trial: 1. Best value: -0.97428:   8%|▊         | 5/60 [00:49<10:37, 11.59s/it]

[I 2026-03-09 21:15:37,440] Trial 4 finished with value: -0.9758115142627656 and parameters: {'n_estimators': 4351, 'learning_rate': 0.013940346079873234, 'max_depth': 8, 'min_child_weight': 9.362897381052425, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351, 'reg_lambda': 0.0014507434860119778, 'gamma': 9.093204020787821, 'reg_alpha': 1.7828684416997836e-06}. Best is trial 1 with value: -0.9742797887563178.

Best trial: 1. Best value: -0.97428:  10%|█         | 6/60 [01:02<10:55, 12.14s/it]

[I 2026-03-09 21:15:50,651] Trial 5 finished with value: -0.9762940348753354 and parameters: {'n_estimators': 8288, 'learning_rate': 0.028869220380495747, 'max_depth': 6, 'min_child_weight': 11.387495307522313, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'reg_lambda': 4.388598863942796, 'gamma': 9.394989415641891, 'reg_alpha': 0.6082418248172017}. Best is trial 1 with value: -0.9742797887563178.

Best trial: 1. Best value: -0.97428:  12%|█▏        | 7/60 [01:04<07:48,  8.83s/it]

[I 2026-03-09 21:15:52,658] Trial 6 finished with value: -0.9751917513874545 and parameters: {'n_estimators': 7577, 'learning_rate': 0.22999586428143728, 'max_depth': 2, 'min_child_weight': 4.723674385963759, 'subsample': 0.522613644455269, 'colsample_bytree': 0.6626651653816322, 'reg_lambda': 0.06704755197530224, 'gamma': 2.713490317738959, 'reg_alpha': 0.16186864586521713}. Best is trial 1 with value: -0.9742797887563178.

Best trial: 1. Best value: -0.97428:  13%|█▎        | 8/60 [01:19<09:12, 10.63s/it]

[I 2026-03-09 21:16:07,151] Trial 7 finished with value: -0.9773313005427765 and parameters: {'n_estimators': 4924, 'learning_rate': 0.026000059117302653, 'max_depth': 6, 'min_child_weight': 3.6775602745204905, 'subsample': 0.9010984903770198, 'colsample_bytree': 0.5372753218398854, 'reg_lambda': 43.38624983446471, 'gamma': 7.722447692966574, 'reg_alpha': 5.35330210833913e-07}. Best is trial 1 with value: -0.9742797887563178.

Best trial: 1. Best value: -0.97428:  15%|█▌        | 9/60 [01:21<06:50,  8.05s/it]

[I 2026-03-09 21:16:09,533] Trial 8 finished with value: -0.9851796323378158 and parameters: {'n_estimators': 1060, 'learning_rate': 0.1601531217136121, 'max_depth': 8, 'min_child_weight': 14.851136192778759, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.5370223258670452, 'reg_lambda': 0.04835258599682954, 'gamma': 1.1586905952512971, 'reg_alpha': 0.32218907673802705}. Best is trial 1 with value: -0.9742797887563178.

Best trial: 1. Best value: -0.97428:  17%|█▋        | 10/60 [01:31<07:10,  8.62s/it]

[I 2026-03-09 21:16:19,417] Trial 9 finished with value: -0.9759236156700887 and parameters: {'n_estimators': 7856, 'learning_rate': 0.030816017044468066, 'max_depth': 2, 'min_child_weight': 6.908664112597582, 'subsample': 0.6625916610133735, 'colsample_bytree': 0.864803089169032, 'reg_lambda': 0.9905204218383901, 'gamma': 8.872127425763265, 'reg_alpha': 0.00012816913980027156}. Best is trial 1 with value: -0.9742797887563178.

Best trial: 10. Best value: -0.973652:  18%|█▊        | 11/60 [01:42<07:29,  9.17s/it]

[I 2026-03-09 21:16:29,843] Trial 10 finished with value: -0.973651682532147 and parameters: {'n_estimators': 11648, 'learning_rate': 0.010206070557577008, 'max_depth': 10, 'min_child_weight': 19.099035406164262, 'subsample': 0.7728591400411078, 'colsample_bytree': 0.8451235367845726, 'reg_lambda': 0.01586065617088683, 'gamma': 4.040260720186448, 'reg_alpha': 0.0001476979035328468}. Best is trial 10 with value: -0.973651682532147.

Best trial: 10. Best value: -0.973652:  20%|██        | 12/60 [01:53<07:54,  9.88s/it]

[I 2026-03-09 21:16:41,355] Trial 11 finished with value: -0.9738087237854017 and parameters: {'n_estimators': 11973, 'learning_rate': 0.010290509463842875, 'max_depth': 10, 'min_child_weight': 19.453087854793978, 'subsample': 0.7692492775881494, 'colsample_bytree': 0.8513496163789993, 'reg_lambda': 0.008699835186758723, 'gamma': 4.635918553211216, 'reg_alpha': 0.00016041579399185833}. Best is trial 10 with value: -0.973651682532147.

Best trial: 10. Best value: -0.973652:  22%|██▏       | 13/60 [02:05<08:11, 10.45s/it]

[I 2026-03-09 21:16:53,113] Trial 12 finished with value: -0.9740258955429187 and parameters: {'n_estimators': 11640, 'learning_rate': 0.01609037845749139, 'max_depth': 10, 'min_child_weight': 19.976538478608365, 'subsample': 0.7734942910835931, 'colsample_bytree': 0.8588729908849949, 'reg_lambda': 0.01096691760117074, 'gamma': 5.615195711001008, 'reg_alpha': 2.7038645163679392e-05}. Best is trial 10 with value: -0.973651682532147.

Best trial: 10. Best value: -0.973652:  23%|██▎       | 14/60 [02:09<06:36,  8.62s/it]

[I 2026-03-09 21:16:57,486] Trial 13 finished with value: -0.9739549536533056 and parameters: {'n_estimators': 11957, 'learning_rate': 0.06372126605598076, 'max_depth': 10, 'min_child_weight': 19.987886334189472, 'subsample': 0.7783018090268713, 'colsample_bytree': 0.8585787245031458, 'reg_lambda': 0.013688972761036162, 'gamma': 5.293469466158547, 'reg_alpha': 0.006643489683070774}. Best is trial 10 with value: -0.973651682532147.

Best trial: 10. Best value: -0.973652:  25%|██▌       | 15/60 [02:17<06:19,  8.42s/it]

[I 2026-03-09 21:17:05,463] Trial 14 finished with value: -0.9763423873999818 and parameters: {'n_estimators': 10084, 'learning_rate': 0.010434934234060706, 'max_depth': 9, 'min_child_weight': 16.996789227587776, 'subsample': 0.997344085519017, 'colsample_bytree': 0.9501945220447685, 'reg_lambda': 0.4224523984972838, 'gamma': 3.849679031223864, 'reg_alpha': 2.2178876149178944e-05}. Best is trial 10 with value: -0.973651682532147.

Best trial: 10. Best value: -0.973652:  27%|██▋       | 16/60 [02:29<06:57,  9.48s/it]

[I 2026-03-09 21:17:17,402] Trial 15 finished with value: -0.9744585810958878 and parameters: {'n_estimators': 10279, 'learning_rate': 0.019293369292093035, 'max_depth': 4, 'min_child_weight': 17.17162983766685, 'subsample': 0.7136008139243853, 'colsample_bytree': 0.7967239373760329, 'reg_lambda': 0.02845285718555622, 'gamma': 6.412492882382235, 'reg_alpha': 0.009046175174362753}. Best is trial 10 with value: -0.973651682532147.

Best trial: 10. Best value: -0.973652:  28%|██▊       | 17/60 [02:36<06:10,  8.62s/it]

[I 2026-03-09 21:17:24,026] Trial 16 finished with value: -0.981636296314272 and parameters: {'n_estimators': 10033, 'learning_rate': 0.044440544323158186, 'max_depth': 9, 'min_child_weight': 14.47136729047585, 'subsample': 0.8375365702343569, 'colsample_bytree': 0.9131414471653481, 'reg_lambda': 0.004051073940276832, 'gamma': 0.27219026391196977, 'reg_alpha': 1.3021037527817063e-08}. Best is trial 10 with value: -0.973651682532147.

Best trial: 17. Best value: -0.973364:  30%|███       | 18/60 [02:40<05:12,  7.44s/it]

[I 2026-03-09 21:17:28,722] Trial 17 finished with value: -0.9733638005574722 and parameters: {'n_estimators': 10959, 'learning_rate': 0.044207413119892784, 'max_depth': 5, 'min_child_weight': 18.402185734984965, 'subsample': 0.7165356529646334, 'colsample_bytree': 0.7847849004475568, 'reg_lambda': 0.2406170677141267, 'gamma': 4.51969624949704, 'reg_alpha': 4.724398598434663e-06}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  32%|███▏      | 19/60 [02:43<04:03,  5.94s/it]

[I 2026-03-09 21:17:31,152] Trial 18 finished with value: -0.9749817976365321 and parameters: {'n_estimators': 3250, 'learning_rate': 0.0969193339743378, 'max_depth': 4, 'min_child_weight': 9.222166612429337, 'subsample': 0.7222057612578134, 'colsample_bytree': 0.7507285077111833, 'reg_lambda': 1.1691910368806715, 'gamma': 1.9079788217819122, 'reg_alpha': 2.4463743662914683e-08}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  33%|███▎      | 20/60 [02:51<04:19,  6.49s/it]

[I 2026-03-09 21:17:38,936] Trial 19 finished with value: -0.9750758496149097 and parameters: {'n_estimators': 10687, 'learning_rate': 0.04302553031342478, 'max_depth': 4, 'min_child_weight': 14.869310887875518, 'subsample': 0.8306501003915426, 'colsample_bytree': 0.7866804535238765, 'reg_lambda': 0.2193059760478956, 'gamma': 6.538839629254709, 'reg_alpha': 4.360457560669901e-06}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  35%|███▌      | 21/60 [02:55<03:43,  5.74s/it]

[I 2026-03-09 21:17:42,925] Trial 20 finished with value: -0.974943915428063 and parameters: {'n_estimators': 9169, 'learning_rate': 0.1393124666240838, 'max_depth': 5, 'min_child_weight': 17.892824083102138, 'subsample': 0.6754907927896419, 'colsample_bytree': 0.6792592433508007, 'reg_lambda': 5.409055426910545, 'gamma': 3.9442448445003615, 'reg_alpha': 4.41986064091097}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  37%|███▋      | 22/60 [03:02<04:01,  6.37s/it]

[I 2026-03-09 21:17:50,752] Trial 21 finished with value: -0.9737840987135051 and parameters: {'n_estimators': 11705, 'learning_rate': 0.01895072131273925, 'max_depth': 9, 'min_child_weight': 18.6456106106453, 'subsample': 0.8132099751939573, 'colsample_bytree': 0.8122873365280193, 'reg_lambda': 0.02241701215335067, 'gamma': 4.163277297894667, 'reg_alpha': 0.00012215328506960758}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  38%|███▊      | 23/60 [03:08<03:49,  6.20s/it]

[I 2026-03-09 21:17:56,549] Trial 22 finished with value: -0.9734233991244311 and parameters: {'n_estimators': 10777, 'learning_rate': 0.019783960737211077, 'max_depth': 9, 'min_child_weight': 18.259859814335062, 'subsample': 0.8157808771928156, 'colsample_bytree': 0.8033348792290621, 'reg_lambda': 0.029465461235150706, 'gamma': 3.5223655075162084, 'reg_alpha': 1.649431023757211e-05}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  40%|████      | 24/60 [03:12<03:11,  5.32s/it]

[I 2026-03-09 21:17:59,834] Trial 23 finished with value: -0.9762138447826096 and parameters: {'n_estimators': 10825, 'learning_rate': 0.03767296346137706, 'max_depth': 6, 'min_child_weight': 1.3479317637197177, 'subsample': 0.8962491643939959, 'colsample_bytree': 0.7463367214037204, 'reg_lambda': 0.09345136363149657, 'gamma': 2.470982594010135, 'reg_alpha': 1.2316166154264642e-05}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  42%|████▏     | 25/60 [03:18<03:14,  5.57s/it]

[I 2026-03-09 21:18:05,986] Trial 24 finished with value: -0.9743307577478684 and parameters: {'n_estimators': 9427, 'learning_rate': 0.015051638978392508, 'max_depth': 7, 'min_child_weight': 15.851736963856503, 'subsample': 0.7173977827786409, 'colsample_bytree': 0.924563859092338, 'reg_lambda': 0.5912960791799332, 'gamma': 3.310715164455706, 'reg_alpha': 1.0646906086458347e-07}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  43%|████▎     | 26/60 [03:30<04:19,  7.65s/it]

[I 2026-03-09 21:18:18,473] Trial 25 finished with value: -0.9762421585091511 and parameters: {'n_estimators': 11146, 'learning_rate': 0.02228604070936695, 'max_depth': 5, 'min_child_weight': 13.548580795290125, 'subsample': 0.9625632338704708, 'colsample_bytree': 0.815439043254126, 'reg_lambda': 0.03291349620112738, 'gamma': 6.074218650298464, 'reg_alpha': 0.0005745722010340215}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  45%|████▌     | 27/60 [03:41<04:39,  8.48s/it]

[I 2026-03-09 21:18:28,900] Trial 26 finished with value: -0.9740481691191526 and parameters: {'n_estimators': 9590, 'learning_rate': 0.01370337317342075, 'max_depth': 7, 'min_child_weight': 18.226850809151152, 'subsample': 0.8084882566361624, 'colsample_bytree': 0.7037821494441554, 'reg_lambda': 0.0039312107092296525, 'gamma': 4.802414686211625, 'reg_alpha': 4.717096453775717e-06}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  47%|████▋     | 28/60 [03:43<03:36,  6.78s/it]

[I 2026-03-09 21:18:31,710] Trial 27 finished with value: -0.9754689293091214 and parameters: {'n_estimators': 7146, 'learning_rate': 0.06280700533351116, 'max_depth': 3, 'min_child_weight': 15.925247320412252, 'subsample': 0.8612860166893069, 'colsample_bytree': 0.9059897920248182, 'reg_lambda': 0.2103893389230672, 'gamma': 1.4698881067465304, 'reg_alpha': 5.490259427907384e-07}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  48%|████▊     | 29/60 [03:47<03:02,  5.90s/it]

[I 2026-03-09 21:18:35,562] Trial 28 finished with value: -0.9746332210590998 and parameters: {'n_estimators': 10938, 'learning_rate': 0.034385556340785106, 'max_depth': 9, 'min_child_weight': 18.617164209659833, 'subsample': 0.7374256534648187, 'colsample_bytree': 0.7709842290984592, 'reg_lambda': 2.434190689791943, 'gamma': 3.444809619325304, 'reg_alpha': 4.374641544098187e-05}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  50%|█████     | 30/60 [03:50<02:32,  5.10s/it]

[I 2026-03-09 21:18:38,788] Trial 29 finished with value: -0.9738388640159507 and parameters: {'n_estimators': 9083, 'learning_rate': 0.09584117536519747, 'max_depth': 5, 'min_child_weight': 13.55275212670096, 'subsample': 0.6884566815522322, 'colsample_bytree': 0.619720671481651, 'reg_lambda': 0.0034810878285586122, 'gamma': 4.5129956536366365, 'reg_alpha': 0.0016652517071094285}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  52%|█████▏    | 31/60 [03:56<02:34,  5.34s/it]

[I 2026-03-09 21:18:44,701] Trial 30 finished with value: -0.9764513771051666 and parameters: {'n_estimators': 8385, 'learning_rate': 0.05000009762381175, 'max_depth': 8, 'min_child_weight': 15.562131042825747, 'subsample': 0.9268782005699934, 'colsample_bytree': 0.8266718297548705, 'reg_lambda': 0.001059411990391457, 'gamma': 7.223574198499623, 'reg_alpha': 0.012680027566317633}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  53%|█████▎    | 32/60 [04:04<02:47,  5.97s/it]

[I 2026-03-09 21:18:52,131] Trial 31 finished with value: -0.9735699787062762 and parameters: {'n_estimators': 11247, 'learning_rate': 0.019526012525505454, 'max_depth': 9, 'min_child_weight': 18.74903983111192, 'subsample': 0.8108935820171131, 'colsample_bytree': 0.7209006612244687, 'reg_lambda': 0.018342946276172716, 'gamma': 4.310940496625439, 'reg_alpha': 8.928174157806916e-05}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  55%|█████▌    | 33/60 [04:09<02:36,  5.78s/it]

[I 2026-03-09 21:18:57,482] Trial 32 finished with value: -0.9767172456717119 and parameters: {'n_estimators': 11296, 'learning_rate': 0.021793190071613802, 'max_depth': 9, 'min_child_weight': 16.85247467332912, 'subsample': 0.8002909474624987, 'colsample_bytree': 0.7122309235479091, 'reg_lambda': 0.01713698522286772, 'gamma': 2.255041767799608, 'reg_alpha': 0.0016873196452745942}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  57%|█████▋    | 34/60 [04:21<03:14,  7.49s/it]

[I 2026-03-09 21:19:08,960] Trial 33 finished with value: -0.9740282788670693 and parameters: {'n_estimators': 10238, 'learning_rate': 0.018753260199202402, 'max_depth': 10, 'min_child_weight': 18.618842947772638, 'subsample': 0.7538562686676777, 'colsample_bytree': 0.6390298981315483, 'reg_lambda': 0.0986434198233455, 'gamma': 5.5147772219999425, 'reg_alpha': 6.402997352729247e-06}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  58%|█████▊    | 35/60 [04:28<03:09,  7.56s/it]

[I 2026-03-09 21:19:16,695] Trial 34 finished with value: -0.9738647462976457 and parameters: {'n_estimators': 10588, 'learning_rate': 0.012531167062334841, 'max_depth': 7, 'min_child_weight': 17.679256067050968, 'subsample': 0.8466743730518109, 'colsample_bytree': 0.7186346313916543, 'reg_lambda': 0.051346146410124735, 'gamma': 3.1898922730710004, 'reg_alpha': 0.0005107489767932526}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  60%|██████    | 36/60 [04:39<03:20,  8.35s/it]

[I 2026-03-09 21:19:26,877] Trial 35 finished with value: -0.973589009035997 and parameters: {'n_estimators': 11117, 'learning_rate': 0.012068941317670214, 'max_depth': 8, 'min_child_weight': 18.91086906378383, 'subsample': 0.792131691204414, 'colsample_bytree': 0.7692928511067179, 'reg_lambda': 0.0057707034330911665, 'gamma': 3.9971441694206953, 'reg_alpha': 7.070192064953561e-05}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  62%|██████▏   | 37/60 [04:44<02:52,  7.52s/it]

[I 2026-03-09 21:19:32,463] Trial 36 finished with value: -0.9736041579040517 and parameters: {'n_estimators': 9610, 'learning_rate': 0.024557077942615795, 'max_depth': 8, 'min_child_weight': 16.63367684253671, 'subsample': 0.639645592642198, 'colsample_bytree': 0.7670655959119331, 'reg_lambda': 0.006492075843650814, 'gamma': 4.879735352677062, 'reg_alpha': 1.609329637026341e-06}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  63%|██████▎   | 38/60 [04:51<02:39,  7.24s/it]

[I 2026-03-09 21:19:39,057] Trial 37 finished with value: -0.973553564875403 and parameters: {'n_estimators': 8672, 'learning_rate': 0.016341398387125117, 'max_depth': 8, 'min_child_weight': 11.12558112079184, 'subsample': 0.625796303597987, 'colsample_bytree': 0.7349792707666731, 'reg_lambda': 0.0020595116457134475, 'gamma': 3.6300203858142965, 'reg_alpha': 1.564414635367493e-06}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  65%|██████▌   | 39/60 [04:57<02:26,  6.97s/it]

[I 2026-03-09 21:19:45,402] Trial 38 finished with value: -0.9742541730016677 and parameters: {'n_estimators': 6115, 'learning_rate': 0.016007212790129958, 'max_depth': 9, 'min_child_weight': 9.253367490876531, 'subsample': 0.6215169684736621, 'colsample_bytree': 0.7269602004460272, 'reg_lambda': 0.002050274497976205, 'gamma': 2.8434152846415843, 'reg_alpha': 1.7059261762779812e-07}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  67%|██████▋   | 40/60 [05:01<02:03,  6.16s/it]

[I 2026-03-09 21:19:49,653] Trial 39 finished with value: -0.973460285462111 and parameters: {'n_estimators': 8535, 'learning_rate': 0.028884876854199243, 'max_depth': 8, 'min_child_weight': 7.353856272191632, 'subsample': 0.5485378859389886, 'colsample_bytree': 0.5889074451540846, 'reg_lambda': 0.0021453600047147314, 'gamma': 3.532902559134924, 'reg_alpha': 8.858581467767245e-07}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 17. Best value: -0.973364:  68%|██████▊   | 41/60 [05:07<01:53,  5.99s/it]

[I 2026-03-09 21:19:55,260] Trial 40 finished with value: -0.9773526479747332 and parameters: {'n_estimators': 8549, 'learning_rate': 0.031084615791975193, 'max_depth': 7, 'min_child_weight': 7.269047812153083, 'subsample': 0.5590573002007949, 'colsample_bytree': 0.5778610056515864, 'reg_lambda': 0.002094610880138388, 'gamma': 1.0160285551328188, 'reg_alpha': 1.7087990674357393e-06}. Best is trial 17 with value: -0.9733638005574722.

Best trial: 41. Best value: -0.973216:  70%|███████   | 42/60 [05:11<01:38,  5.50s/it]

[I 2026-03-09 21:19:59,601] Trial 41 finished with value: -0.9732155657230992 and parameters: {'n_estimators': 6718, 'learning_rate': 0.02592761824499548, 'max_depth': 8, 'min_child_weight': 10.66463057193618, 'subsample': 0.5194786772638014, 'colsample_bytree': 0.577263967511964, 'reg_lambda': 0.0023480865799038668, 'gamma': 3.4797243006105525, 'reg_alpha': 2.860388515698147e-07}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  72%|███████▏  | 43/60 [05:15<01:24,  4.99s/it]

[I 2026-03-09 21:20:03,415] Trial 42 finished with value: -0.9738353618700886 and parameters: {'n_estimators': 7379, 'learning_rate': 0.026638141996792927, 'max_depth': 8, 'min_child_weight': 10.512704512340218, 'subsample': 0.5097778936068785, 'colsample_bytree': 0.5052846435897602, 'reg_lambda': 0.001194749729566059, 'gamma': 3.4966584382591703, 'reg_alpha': 7.964661734404748e-08}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  73%|███████▎  | 44/60 [05:19<01:15,  4.73s/it]

[I 2026-03-09 21:20:07,543] Trial 43 finished with value: -0.9756498266638861 and parameters: {'n_estimators': 6845, 'learning_rate': 0.035475489026533184, 'max_depth': 6, 'min_child_weight': 7.730907835487421, 'subsample': 0.5448346857776651, 'colsample_bytree': 0.5892136867100068, 'reg_lambda': 0.0020967371264810964, 'gamma': 1.924190498163437, 'reg_alpha': 5.173394067482386e-07}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  75%|███████▌  | 45/60 [05:23<01:04,  4.31s/it]

[I 2026-03-09 21:20:10,864] Trial 44 finished with value: -0.9754581792526473 and parameters: {'n_estimators': 8038, 'learning_rate': 0.04275771697509509, 'max_depth': 7, 'min_child_weight': 6.0006789762756885, 'subsample': 0.58683829323731, 'colsample_bytree': 0.6336119596581145, 'reg_lambda': 0.003976299602994115, 'gamma': 2.9808687273848262, 'reg_alpha': 2.759717628716596e-07}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  77%|███████▋  | 46/60 [05:27<00:59,  4.28s/it]

[I 2026-03-09 21:20:15,081] Trial 45 finished with value: -0.973249340658642 and parameters: {'n_estimators': 5536, 'learning_rate': 0.029004237059432583, 'max_depth': 7, 'min_child_weight': 12.392529430017454, 'subsample': 0.5299319638228099, 'colsample_bytree': 0.5689643633824825, 'reg_lambda': 0.002689192554178053, 'gamma': 3.6810306747939743, 'reg_alpha': 1.2379684652987558e-06}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  78%|███████▊  | 47/60 [05:32<01:00,  4.64s/it]

[I 2026-03-09 21:20:20,555] Trial 46 finished with value: -0.9737843566709975 and parameters: {'n_estimators': 5201, 'learning_rate': 0.03001854714970993, 'max_depth': 7, 'min_child_weight': 12.64624579977968, 'subsample': 0.5305631378071723, 'colsample_bytree': 0.5583946167646959, 'reg_lambda': 0.007678479656688285, 'gamma': 5.201949248690228, 'reg_alpha': 1.2247292144991026e-05}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  80%|████████  | 48/60 [05:35<00:49,  4.13s/it]

[I 2026-03-09 21:20:23,496] Trial 47 finished with value: -0.9751961573190636 and parameters: {'n_estimators': 3872, 'learning_rate': 0.051049256484570364, 'max_depth': 5, 'min_child_weight': 11.699486609596764, 'subsample': 0.5690616004538265, 'colsample_bytree': 0.5046656495808448, 'reg_lambda': 0.03770911563948275, 'gamma': 2.6376715532555837, 'reg_alpha': 5.58834547853874e-08}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  82%|████████▏ | 49/60 [05:43<00:58,  5.30s/it]

[I 2026-03-09 21:20:31,531] Trial 48 finished with value: -0.9738404603783153 and parameters: {'n_estimators': 5521, 'learning_rate': 0.024137576355957993, 'max_depth': 6, 'min_child_weight': 8.020510574970729, 'subsample': 0.5026687570007776, 'colsample_bytree': 0.5538898061598031, 'reg_lambda': 0.3733928629050413, 'gamma': 5.849950722594186, 'reg_alpha': 4.737174362949277e-07}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  83%|████████▎ | 50/60 [05:48<00:52,  5.24s/it]

[I 2026-03-09 21:20:36,639] Trial 49 finished with value: -0.973735923346497 and parameters: {'n_estimators': 6381, 'learning_rate': 0.03908597552039974, 'max_depth': 8, 'min_child_weight': 10.07999812565279, 'subsample': 0.6053536947135603, 'colsample_bytree': 0.61544324995944, 'reg_lambda': 0.0030058026860383356, 'gamma': 4.451541697313928, 'reg_alpha': 3.551601020261932e-06}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  85%|████████▌ | 51/60 [05:56<00:53,  5.91s/it]

[I 2026-03-09 21:20:44,098] Trial 50 finished with value: -0.9745992053967563 and parameters: {'n_estimators': 2618, 'learning_rate': 0.06601418594204116, 'max_depth': 7, 'min_child_weight': 6.020986304138294, 'subsample': 0.5366307132545004, 'colsample_bytree': 0.8787451754794509, 'reg_lambda': 0.13440275806156335, 'gamma': 8.274286769211272, 'reg_alpha': 1.1347696406100089e-06}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  87%|████████▋ | 52/60 [06:01<00:44,  5.59s/it]

[I 2026-03-09 21:20:48,936] Trial 51 finished with value: -0.97354221592628 and parameters: {'n_estimators': 4586, 'learning_rate': 0.028102440754181977, 'max_depth': 8, 'min_child_weight': 11.014949142126152, 'subsample': 0.6202177566671218, 'colsample_bytree': 0.6035155678399555, 'reg_lambda': 0.010112413860599015, 'gamma': 3.71632027412264, 'reg_alpha': 9.629297153427189e-07}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  88%|████████▊ | 53/60 [06:05<00:36,  5.14s/it]

[I 2026-03-09 21:20:53,045] Trial 52 finished with value: -0.9737190486947099 and parameters: {'n_estimators': 4502, 'learning_rate': 0.02867943459878527, 'max_depth': 8, 'min_child_weight': 8.459542319531304, 'subsample': 0.5519037093056686, 'colsample_bytree': 0.5689040451593206, 'reg_lambda': 0.010978716477315067, 'gamma': 3.669577693309218, 'reg_alpha': 3.215606546402508e-08}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  90%|█████████ | 54/60 [06:08<00:28,  4.73s/it]

[I 2026-03-09 21:20:56,812] Trial 53 finished with value: -0.9744806355701423 and parameters: {'n_estimators': 6003, 'learning_rate': 0.033115863488701186, 'max_depth': 9, 'min_child_weight': 12.188213086627949, 'subsample': 0.579212347098345, 'colsample_bytree': 0.6066806024104954, 'reg_lambda': 0.00563780833126651, 'gamma': 3.1742384691135093, 'reg_alpha': 1.278400399852819e-05}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  92%|█████████▏| 55/60 [06:15<00:26,  5.35s/it]

[I 2026-03-09 21:21:03,609] Trial 54 finished with value: -0.9736893141593862 and parameters: {'n_estimators': 4885, 'learning_rate': 0.02203589828785998, 'max_depth': 7, 'min_child_weight': 10.388895750367483, 'subsample': 0.5173676771514281, 'colsample_bytree': 0.5235739953589247, 'reg_lambda': 0.0013562475327439157, 'gamma': 5.14829394471832, 'reg_alpha': 2.747987080083354e-07}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  93%|█████████▎| 56/60 [06:20<00:20,  5.22s/it]

[I 2026-03-09 21:21:08,539] Trial 55 finished with value: -0.97634862409872 and parameters: {'n_estimators': 3796, 'learning_rate': 0.02643103949932898, 'max_depth': 8, 'min_child_weight': 3.6525667454100037, 'subsample': 0.6051427946644501, 'colsample_bytree': 0.6615167847721725, 'reg_lambda': 0.002807944949960677, 'gamma': 2.4715686191454003, 'reg_alpha': 3.5567654099427135e-06}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  95%|█████████▌| 57/60 [06:24<00:14,  4.93s/it]

[I 2026-03-09 21:21:12,772] Trial 56 finished with value: -0.9738740497765802 and parameters: {'n_estimators': 5667, 'learning_rate': 0.0461292733474603, 'max_depth': 9, 'min_child_weight': 12.878523623876719, 'subsample': 0.5671972010941652, 'colsample_bytree': 0.5986391643519058, 'reg_lambda': 0.008984056368681043, 'gamma': 4.143421152803514, 'reg_alpha': 7.773972816499439e-07}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  97%|█████████▋| 58/60 [06:28<00:08,  4.50s/it]

[I 2026-03-09 21:21:16,268] Trial 57 finished with value: -0.9745403356814769 and parameters: {'n_estimators': 2312, 'learning_rate': 0.039631427917270555, 'max_depth': 6, 'min_child_weight': 2.0608343243125997, 'subsample': 0.667287603559271, 'colsample_bytree': 0.5413542982124289, 'reg_lambda': 22.50775294330244, 'gamma': 2.096620254312363, 'reg_alpha': 1.96163635132027e-07}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 41. Best value: -0.973216:  98%|█████████▊| 59/60 [06:31<00:04,  4.10s/it]

[I 2026-03-09 21:21:19,446] Trial 58 finished with value: -0.9741757650094727 and parameters: {'n_estimators': 7727, 'learning_rate': 0.057245502785704006, 'max_depth': 8, 'min_child_weight': 10.992491979986042, 'subsample': 0.6882232331299647, 'colsample_bytree': 0.6628337668338861, 'reg_lambda': 0.005174320312247845, 'gamma': 3.7479576797913885, 'reg_alpha': 6.747491278803308e-06}. Best is trial 41 with value: -0.9732155657230992.

Best trial: 59. Best value: -0.973063: 100%|██████████| 60/60 [06:38<00:00,  6.64s/it]

[I 2026-03-09 21:21:26,419] Trial 59 finished with value: -0.9730629466290394 and parameters: {'n_estimators': 4332, 'learning_rate': 0.01789269576971008, 'max_depth': 10, 'min_child_weight': 4.825799127549914, 'subsample': 0.5300916575240049, 'colsample_bytree': 0.5883615110150762, 'reg_lambda': 0.02516502304244902, 'gamma': 4.614151718031739, 'reg_alpha': 2.5605700319869678e-06}. Best is trial 59 with value: -0.9730629466290394.

Best CV neg_log_loss: -0.9730629466290394
Best params:
 {'n_estimators': 4332, 'learning_rate': 0.01789269576971008, 'max_depth': 10, 'min_child_weight': 4.825799127549914, 'subsample': 0.5300916575240049, 'colsample_bytree': 0.5883615110150762, 'reg_lambda': 0.02516502304244902, 'gamma': 4.614151718031739, 'reg_alpha': 2.5605700319869678e-06}
[0]	validation_0-mlogloss:1.07076

[100]	validation_0-mlogloss:0.98523
[200]	validation_0-mlogloss:0.97929
[300]	validation_0-mlogloss:0.97921
[400]	validation_0-mlogloss:0.97936
[441]	validation_0-mlogloss:0.97930

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.5883615110150762, device=None,
              early_stopping_rounds=200, enable_categorical=False,
              eval_metric='mlogloss', feature_types=None, feature_weights=None,
              gamma=4.614151718031739, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01789269576971008,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=10, max_leaves=None,
              min_child_weight=4.825799127549914, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=4332,
              n_jobs=-1, num_class=3, ...)

In [36]:
# metrics
proba_xb_o = model_xb_opt.predict_proba(X_test)
pred_xb_o = proba_xb_o.argmax(axis=1)

print("\nAccuracy:", accuracy_score(y_test, pred_xb_o))
print("LogLoss:", log_loss(y_test, proba_xb_o))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_xb_o))
print("\nClassification Report:\n", classification_report(y_test, pred_xb_o, digits=3))

Accuracy: 0.5310492505353319
LogLoss: 0.9789725151040787

Confusion Matrix:
 [[663   0 146]
 [283   0 147]
 [300   0 329]]

Classification Report:
               precision    recall  f1-score   support

           0      0.532     0.820     0.645       809
           1      0.000     0.000     0.000       430
           2      0.529     0.523     0.526       629

    accuracy                          0.531      1868
   macro avg      0.354     0.448     0.390      1868
weighted avg      0.409     0.531     0.457      1868

c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\mikko\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [37]:
proba_xgbo_opt_rng = model_xb_opt.predict_proba(X_test)

rng_xgbo = np.random.default_rng(42)

pred_xgbo_opt_rng = np.array([
    rng.choice(len(p), p=p) for p in proba_xgbo_opt_rng
])

In [38]:
print("TEST Accuracy:", accuracy_score(y_test, pred_xgbo_opt_rng))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred_xgbo_opt_rng))
print("\nClassification Report:\n", classification_report(y_test, pred_xgbo_opt_rng, digits=3))

TEST Accuracy: 0.45610278372591007

Confusion Matrix:
 [[459 168 182]
 [185 123 122]
 [226 133 270]]

Classification Report:
               precision    recall  f1-score   support

           0      0.528     0.567     0.547       809
           1      0.290     0.286     0.288       430
           2      0.470     0.429     0.449       629

    accuracy                          0.456      1868
   macro avg      0.429     0.428     0.428      1868
weighted avg      0.454     0.456     0.454      1868

In [39]:
X_xb_o_last = X_test.iloc[[-1]]   # double brackets keep it 2D

pred_xb_o_last = model_xb_opt.predict(X_xb_o_last)
proba_xb_o_last = model_xb_opt.predict_proba(X_xb_o_last)

print("Predicted class:", pred_xb_o_last)
print("Probabilities:", proba_xb_o_last)

Predicted class: [2]
Probabilities: [[0.304218   0.25660953 0.43917248]]